<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Student2;
use App\Administrative;
use App\Usuario;

class CorreosEstudiantesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = array(
			['nombres'=>'MIA VALENTINA','apellidos'=>'VILLEGAS PONCE','correo'=>'mia.villegas@pined.ec'],
			['nombres'=>'YIRETH VALENTINA','apellidos'=>'ACOSTA ARREAGA','correo'=>'yireth.acosta@pined.ec'],
			['nombres'=>'KARIM SAID','apellidos'=>'AZHIR MORALES','correo'=>'karimazhir@pined.com'],
			['nombres'=>'AMBAR ROMINA','apellidos'=>'JARA ORMEÑO','correo'=>'ambar.jara@pined.ec'],
			['nombres'=>'ASHLEY VALENTINA','apellidos'=>'TAPIA MIRABA','correo'=>'denissemiraba@pined.com'],
			['nombres'=>'ISAAC DAVID','apellidos'=>'VERA LOOR','correo'=>'isaac.vera@pined.ec'],
			['nombres'=>'LIAN IGNACIO','apellidos'=>'CHANG MACIAS','correo'=>'lian.chang@pined.ec'],
			['nombres'=>'XAVIER MAURICIO','apellidos'=>'ALVARADO ANDRADE','correo'=>'xavier.alvaradoa@pined.ec'],
			['nombres'=>'AMY AINOAH','apellidos'=>'ILLESCAS SALAZAR','correo'=>'amy.illescas@pined.ec'],
			['nombres'=>'JOSH ELISEO','apellidos'=>'QUEVEDO QUIMI','correo'=>'josh.quevedoq@pined.ec'],
			['nombres'=>'ERICKA ALEJANDRA','apellidos'=>'SANTILLAN GARCIA','correo'=>'ericka.santillan@pined.ec'],
			['nombres'=>'DELIA ANDREA','apellidos'=>'CALDERON RAMIREZ','correo'=>'delia.calderon@pined.ec'],
			['nombres'=>'GERARDO GABRIEL','apellidos'=>'PINCAY GAMAZO','correo'=>'gerardo.pincay@pined.ec'],
			['nombres'=>'WILSON IGNACIO','apellidos'=>'CHANG MACIAS','correo'=>'wilson.chang@pined.ec'],
			['nombres'=>'MARIA CAMILA','apellidos'=>'GIRALDO VELASQUEZ','correo'=>'camila.giraldo@pined.ec'],
			['nombres'=>'JUAN SEBASTIAN','apellidos'=>'ROMERO HARO','correo'=>'juan.romero@pined.ec'],
			['nombres'=>'DAYANNA NICOLE','apellidos'=>'ZEA MIÑO','correo'=>'dayanna.zea@pined.ec'],
			['nombres'=>'NADIA VALENTINA','apellidos'=>'PILLASAGUA NEMER','correo'=>'nadia.pillasagua@pined.ec'],
			['nombres'=>'LEANDRO JOSE','apellidos'=>'FLORES MONTERO','correo'=>'leandro.montero@pined.ec'],
			['nombres'=>'RICARDO ALEJANDRO','apellidos'=>'ANDRADE HOLGUIN','correo'=>'ricardo.andrade@pined.ec'],
			['nombres'=>'JOSE ANDRES','apellidos'=>'BELTRAN LABORDE','correo'=>'jose.beltran@pined.ec'],
			['nombres'=>'CAMILA GERALDINE','apellidos'=>'BELTRAN LOPEZ','correo'=>'camila.beltran@pined.ec'],
			['nombres'=>'DEBBIE MABEL','apellidos'=>'CALI GALARZA','correo'=>'debbie.cali@pined.ec'],
			['nombres'=>'MARIA JOSE','apellidos'=>'CAMACHO ESCOBAR','correo'=>'maria.camacho@pined.ec'],
			['nombres'=>'CARLOS MIGUEL','apellidos'=>'CEDEÑO ROMO-LEROUX','correo'=>'carlos.cedeno@pined.ec'],
			['nombres'=>'MARIA EUGENIA','apellidos'=>'CEVALLOS MONROY','correo'=>'maria.cevallos@pined.ec'],
			['nombres'=>'JOHNNY JOSUE','apellidos'=>'CONTRERAS HOLGUIN','correo'=>'johnny.contreras@pined.ec'],
			['nombres'=>'JOSHUA ANDRE','apellidos'=>'DEL VALLE LUNA','correo'=>'joshua.delvalle@pined.ec'],
			['nombres'=>'RICARDO DAVID','apellidos'=>'LOPEZ MATEO','correo'=>'ricardo.lopez@pined.ec'],
			['nombres'=>'SERGIO DAVID','apellidos'=>'MIÑO LIMA','correo'=>'sergio.mino@pined.ec'],
			['nombres'=>'MILENA CAROLINA','apellidos'=>'MONCAYO MACIAS','correo'=>'milena.moncayo@pined.ec'],
			['nombres'=>'NICOLE JAMILEX','apellidos'=>'MOYANO CARVAJAL','correo'=>'nicole.moyano@pined.ec'],
			['nombres'=>'GABRIELA NICOLE','apellidos'=>'OCAÑA MERA','correo'=>'gabriela.ocana@pined.ec'],
			['nombres'=>'ABRAHAM MAURICIO','apellidos'=>'QUINDE ALAVA','correo'=>'abraham.quinde@pined.ec'],
			['nombres'=>'NATALIA GABRIELA','apellidos'=>'RODRIGUEZ ALVAREZ','correo'=>'natalia.rodriguez@pined.ec'],
			['nombres'=>'PAMELA MARINA','apellidos'=>'RODRIGUEZ VELEZ','correo'=>'pamela.rodriguez@pined.ec'],
			['nombres'=>'DANIEL SALVADOR','apellidos'=>'SANCHEZ SOTOMAYOR','correo'=>'daniel.sanchez@pined.ec'],
			['nombres'=>'LETICIA ANTONELLA','apellidos'=>'SANTOS MOSCOSO','correo'=>'leticia.santos@pined.ec'],
			['nombres'=>'MELANNIE DE LOS ANGELES','apellidos'=>'SOLIS CEDEÑO','correo'=>'melannie.solis@pined.ec'],
			['nombres'=>'JOSEPH ALBERTO','apellidos'=>'SPER NUQUES','correo'=>'joseph.sper@pined.ec'],
			['nombres'=>'ALANIS ANAHIS','apellidos'=>'TOLEDO OCEJO','correo'=>'alanis.toledo@pined.ec'],
			['nombres'=>'RICARDO CALEB','apellidos'=>'UQUILLAS CALLE','correo'=>'ricardo.uquillas@pined.ec'],
			['nombres'=>'ANTONELLA VERUSKA','apellidos'=>'VITERI RUIZ','correo'=>'antonella.viteri@pined.ec'],
			['nombres'=>'THADDY DOMENICA','apellidos'=>'ABAD OCEJO','correo'=>'thaddy.abad@pined.ec'],
			['nombres'=>'MOISES EMANUEL','apellidos'=>'ALVAREZ SANCHEZ','correo'=>'moises.alvarez@pined.ec'],
			['nombres'=>'CLAUDIA EMILIA','apellidos'=>'ANDRADE MENDIETA','correo'=>'claudia.andrade@pined.ec'],
			['nombres'=>'DANIELA ALEJANDRA','apellidos'=>'BURGOS CEDEÑO','correo'=>'daniela.burgos@pined.ec'],
			['nombres'=>'NICOLAS JOSUE','apellidos'=>'CABANILLA VACA','correo'=>'nicolas.cabanilla@pined.ec'],
			['nombres'=>'NATALIA ESTEFANIA','apellidos'=>'CEDEÑO ROMO-LEROUX','correo'=>'natalia.cedeno@pined.ec'],
			['nombres'=>'CINTHIA MELISSA','apellidos'=>'CEVALLOS ANZULES','correo'=>'cinthia.cevallos@pined.ec'],
			['nombres'=>'ADRIANA JACQUELINE','apellidos'=>'COELLO GUTIERREZ','correo'=>'adriana.coello@pined.ec'],
			['nombres'=>'ALLISSON LISSETTE','apellidos'=>'DURAN BONILLA','correo'=>'allisson.duran@pined.ec'],
			['nombres'=>'RICARDO JOEL','apellidos'=>'ESPINOZA ESPINALES','correo'=>'ricardo.espinoza@pined.ec'],
			['nombres'=>'DIEGO ANDRES','apellidos'=>'GUACHO ESPINOZA','correo'=>'diego.guacho@pined.ec'],
			['nombres'=>'CAMILA ELIZABETH','apellidos'=>'JARAMILLO ORELLANA','correo'=>'camila.jaramillo@pined.ec'],
			['nombres'=>'NATHALY PAOLA','apellidos'=>'JORDAN YEPEZ','correo'=>'nathaly.jordan@pined.ec'],
			['nombres'=>'JAMILET NASHLY','apellidos'=>'LAINEZ IBAÑEZ','correo'=>'jamilet.lainez@pined.ec'],
			['nombres'=>'MARCELO ESTEBAN','apellidos'=>'LEON VERA','correo'=>'marcelo.leon@pined.ec'],
			['nombres'=>'YAIR JESUS','apellidos'=>'MANRIQUE RODRIGUEZ','correo'=>'yair.manrique@pined.ec'],
			['nombres'=>'DIEGO ALEJANDRO','apellidos'=>'MEDINA SOJOS','correo'=>'diego.medina@pined.ec'],
			['nombres'=>'MARYAM MARLENE','apellidos'=>'MORA MUÑIZ','correo'=>'maryam.mora@pined.ec'],
			['nombres'=>'ANA PAULA','apellidos'=>'MORALES APOLO','correo'=>'ana.morales@pined.ec'],
			['nombres'=>'FRANCISCO MAOL','apellidos'=>'MOSQUERA SANTOS','correo'=>'francisco.mosquera@pined.ec'],
			['nombres'=>'EZEQUIEL DAVID','apellidos'=>'MOSQUERA VILLALA','correo'=>'ezequiel.mosquera@pined.ec'],
			['nombres'=>'IVAN ANDRES','apellidos'=>'PLUAS NAREA','correo'=>'ivan.pluas@pined.ec'],
			['nombres'=>'FABIANA ELIZABETH','apellidos'=>'SANTACRUZ CASTILLO','correo'=>'fabiana.santacruz@pined.ec'],
			['nombres'=>'DANIELA DE LOS ANGELES','apellidos'=>'SUAREZ JIMENEZ','correo'=>'daniela.suarez@pined.ec'],
			['nombres'=>'GUSTAVO GABRIEL','apellidos'=>'SYNCH SANCHEZ','correo'=>'gustavo.synch@pined.ec'],
			['nombres'=>'DANIEL ANDRES','apellidos'=>'TOLEDO PEÑAFIEL','correo'=>'daniel.toledo@pined.ec'],
			['nombres'=>'ANA PAULA','apellidos'=>'TORRES MUÑOZ','correo'=>'ana.torres@pined.ec'],
			['nombres'=>'DENISSE STEPHANIE','apellidos'=>'ZAMORA OROZCO','correo'=>'denisse.zamora@pined.ec'],
			['nombres'=>'NALLELY GEOVANNA','apellidos'=>'ACOSTA ARREAGA','correo'=>'nallely.acosta@pined.ec'],
			['nombres'=>'ALBERTO SEBASTIAN','apellidos'=>'AGUAIS SOTOMAYOR','correo'=>'alberto.aguais@pined.ec'],
			['nombres'=>'SEBASTIAN ARATH','apellidos'=>'ARTEAGA OLAYA','correo'=>'sebastian.arteaga@pined.ec'],
			['nombres'=>'SAMIA SHAYLOTT','apellidos'=>'CANTOS ORTONEDA','correo'=>'samia.cantos@pined.ec'],
			['nombres'=>'MIRKA MADELAINE','apellidos'=>'CARPIO ROBLES','correo'=>'mirka.carpio@pined.ec'],
			['nombres'=>'LUIS ALEJANDRO','apellidos'=>'GAVIDIA  PARRAGA','correo'=>'luis.gavidia@pined.ec'],
			['nombres'=>'JEREMY AXEL','apellidos'=>'GUERRERO RIVAS','correo'=>'jeremy.guerrero@pined.ec'],
			['nombres'=>'ALLISSON VIVIANA','apellidos'=>'IÑIGUEZ TIPAN','correo'=>'allison.iniguez@pined.ec'],
			['nombres'=>'CAMILA CATHERINA','apellidos'=>'LEMA PONCE','correo'=>'camila.lema@pined.ec'],
			['nombres'=>'RAUL ARTURO','apellidos'=>'LEON MORAN','correo'=>'raul.leon@pined.ec'],
			['nombres'=>'SCARLETT VANESSA','apellidos'=>'LUQUE ALAVA','correo'=>'scarlett.luque@pined.ec'],
			['nombres'=>'RENATA DANIELA','apellidos'=>'MARQUEZ VALENCIA','correo'=>'renata.marquez@pined.ec'],
			['nombres'=>'JOSEPH JAMIL','apellidos'=>'MORAN GONGORA','correo'=>'joseph.moran@pined.ec'],
			['nombres'=>'PAOLA VICTORIA','apellidos'=>'MOYANO CAMPAÑA','correo'=>'paola.moyano@pined.ec'],
			['nombres'=>'LUIS ALFREDO','apellidos'=>'MOYANO CARVAJAL','correo'=>'luis.moyano@pined.ec'],
			['nombres'=>'ANGIE NICOLE','apellidos'=>'POZO CEDEÑO','correo'=>'angie.pozo@pined.ec'],
			['nombres'=>'MILENA TAHIS','apellidos'=>'QUEVEDO QUIMI','correo'=>'milena.quevedo@pined.ec'],
			['nombres'=>'SEBASTIAN FARID','apellidos'=>'QUEZADA ZAMORA','correo'=>'sebastian.quezada@pined.ec'],
			['nombres'=>'MELANY TAHIS','apellidos'=>'REMACHE NIETO','correo'=>'melany.remache@pined.ec'],
			['nombres'=>'ELIANA MAITE','apellidos'=>'RUANO POTES','correo'=>'eliana.ruano@pined.ec'],
			['nombres'=>'MILENA PAOLA','apellidos'=>'SALAZAR ORTEGA','correo'=>'milena.salazar@pined.ec'],
			['nombres'=>'ANGELES NAHOMI','apellidos'=>'AVELLAN GANCHOZO','correo'=>'angeles.avellan@pined.ec'],
			['nombres'=>'FRANSHESKA GEOVANNA','apellidos'=>'AVILES LOPEZ','correo'=>'fransheska.aviles@pined.ec'],
			['nombres'=>'LUIS ADRIAN','apellidos'=>'BELTRAN LABORDE','correo'=>'luis.beltran@pined.ec'],
			['nombres'=>'ABEL JARED','apellidos'=>'CARRERA CHERREZ','correo'=>'abel.carrera@pined.ec'],
			['nombres'=>'LENIN GEOVANNY','apellidos'=>'CARRERA QUINCHE','correo'=>'lenin.carrera@pined.ec'],
			['nombres'=>'Melanie Andrea','apellidos'=>'Cerezo Bravo','correo'=>'detsydj10@gmail.com'],
			['nombres'=>'KENNY ALBERTO','apellidos'=>'CHABLA FRANCO','correo'=>'kenny.chabla@pined.ec'],
			['nombres'=>'ROGER FABRICIO','apellidos'=>'LOOR VERA','correo'=>'roger.loor@pined.ec'],
			['nombres'=>'GABRIEL ARTURO','apellidos'=>'MENDOZA BOSQUEZ','correo'=>'gabriel.mendoza@pined.ec'],
			['nombres'=>'ISABEL','apellidos'=>'MONTOYA GONZALEZ','correo'=>'isabel.montoya@pined.ec'],
			['nombres'=>'NICOLE BEATRIZ','apellidos'=>'NAVARRETE ZAMORA','correo'=>'nicole.navarrete@pined.ec'],
			['nombres'=>'ARIADNA NICOLLE','apellidos'=>'PEREZ AGUIRRE','correo'=>'ariadna.perez@pined.ec'],
			['nombres'=>'LUIS ANDRES','apellidos'=>'PLUAS CINO','correo'=>'luis.pluas@pined.ec'],
			['nombres'=>'MANUEL ANDRES','apellidos'=>'RIVERA MONTALVO','correo'=>'manuel.rivera@pined.ec'],
			['nombres'=>'JORGE ENRIQUE','apellidos'=>'VELASQUEZ BURGOS','correo'=>'jorge.velasquez@pined.ec'],
			['nombres'=>'JOSE SALVADOR','apellidos'=>'VELIZ MALDONADO','correo'=>'jose.veliz@pined.ec'],
			['nombres'=>'SAUL IGNACIO','apellidos'=>'VILLACIS ANDRADE','correo'=>'saul.villacis@pined.ec'],
			['nombres'=>'KENNY PAUL','apellidos'=>'YCAZA BRAVO','correo'=>'kenny.ycaza@pined.ec'],
			['nombres'=>'DANIEL ANDRES','apellidos'=>'ZAMBRANO ARMIJOS','correo'=>'daniel.zambrano@pined.ec'],
			['nombres'=>'FIORELLA VALENTINA','apellidos'=>'ACHI LIMONES','correo'=>'fiorella.achi@pined.ec'],
			['nombres'=>'KYONA MARIBETH','apellidos'=>'AYON JUNCO','correo'=>'kyona.ayon@pined.ec'],
			['nombres'=>'NIDIA SALOME','apellidos'=>'ESCOBAR BAJAÑA','correo'=>'nidia.escobar@pined.ec'],
			['nombres'=>'JULIANNA NICOLLE','apellidos'=>'PALACIOS TEJADA','correo'=>'julianna.palacios@pined.ec'],
			['nombres'=>'ARIANA DOMENICA','apellidos'=>'ACOSTA ARREAGA','correo'=>'ariana.acosta@pined.ec'],
			['nombres'=>'SEBASTIAN ELIAS','apellidos'=>'ARELLANO ZAMBRANO','correo'=>'sebastian.arellano@pined.ec'],
			['nombres'=>'AINHOA NATHALIE','apellidos'=>'BETANCOURTH MAGALLANES','correo'=>'ainhoa.betancourth@pined.ec'],
			['nombres'=>'BRITHANY MEHIELL','apellidos'=>'CUEVA CEDEÑO','correo'=>'brithany.cueva@pined.ec'],
			['nombres'=>'DANIELA KARINA','apellidos'=>'FREIRE MIELES','correo'=>'daniela.freire@pined.ec'],
			['nombres'=>'OSCAR LEANDRO','apellidos'=>'GOMEZ DELGADO','correo'=>'oscar.gomez@pined.ec'],
			['nombres'=>'JEREMY DANIEL','apellidos'=>'JARAMILLO VILLACRES','correo'=>'jeremy.jaramillo@pined.ec'],
			['nombres'=>'MARIA PAULA','apellidos'=>'MALDONADO YEPEZ','correo'=>'paula.maldonado@pined.ec'],
			['nombres'=>'ADRIANA ISABEL','apellidos'=>'MUNIZAGA CADENA','correo'=>'adriana.munizaga@pined.ec'],
			['nombres'=>'KEVIN ALEXANDER','apellidos'=>'SERRANO CERON','correo'=>'kevin.serrano@pined.ec'],
			['nombres'=>'CARLOS MANUEL','apellidos'=>'VARELA SANDOVAL','correo'=>'carlos.varela@pined.ec'],
			['nombres'=>'BRITHANY JESLYN','apellidos'=>'ARIAS SALAZAR','correo'=>'brithany.arias@pined.e'],
			['nombres'=>'NICOLE CHRIS','apellidos'=>'BONILLA PINCAY','correo'=>'nicole.bonilla@pined.ec'],
			['nombres'=>'STEPHANY GABRIELA','apellidos'=>'BURGOS LAMILLA','correo'=>'stephany.burgos@pined.ec'],
			['nombres'=>'NESTOR JOSE','apellidos'=>'DIAZ MIELES','correo'=>'nestor.diaz@pined.ec'],
			['nombres'=>'MISAEL RICARDO','apellidos'=>'LLANOS QUIROZ','correo'=>'misael.llanos@pined.ec'],
			['nombres'=>'BRYAN EDUARDO','apellidos'=>'LOPEZ ANDINO','correo'=>'bryan.lopez@pined.ec'],
			['nombres'=>'LEANA MYRHUSKA','apellidos'=>'MOREIRA MIRANDA','correo'=>'leana.moreira@pined.ec'],
			['nombres'=>'MARIA CLARA','apellidos'=>'RAMIREZ DUQUE','correo'=>'maria.ramirez@pined.ec'],
			['nombres'=>'VANESSA ALEJANDRA','apellidos'=>'REYES MORAN','correo'=>'vanessa.reyes@pined.ec'],
			['nombres'=>'ANDREA DENISSE','apellidos'=>'RIVADENEIRA VEGA','correo'=>'andrea.rivadeneira@pined.ec'],
			['nombres'=>'JOSUE EMILIO','apellidos'=>'RUIZ DELGADO','correo'=>'josue.ruiz@pined.ec'],
			['nombres'=>'SUANNY ANTHOANED','apellidos'=>'RUIZ LANDAZURI','correo'=>'suanny.ruiz@pined.ec'],
			['nombres'=>'GABRIEL ORLANDO','apellidos'=>'TOALA GRIJALVA','correo'=>'gabriel.toala@pined.ec'],
			['nombres'=>'JONATHAN ERNESTO','apellidos'=>'VALLEJO PAREDES','correo'=>'jonathan.vallejo@pined.ec'],
			['nombres'=>'GERMAN','apellidos'=>'WONG BRAVO','correo'=>'german.wong@pined.ec'],
			['nombres'=>'JHERSON JEREMY','apellidos'=>'MONJE VELIZ','correo'=>'jherson.monje@pined.ec'],
			['nombres'=>'AMELIA LEOVANA','apellidos'=>'REYES LACA','correo'=>'amelia.reyes@pined.ec'],
			['nombres'=>'MYLEIBA IVANOVA','apellidos'=>'ROJAS CHICA','correo'=>'myleiba.rojas@pined.ec'],
			['nombres'=>'ANGIE JOELY','apellidos'=>'CHINLLI LEMA','correo'=>'angie.chinlli@pined.ec'],
			['nombres'=>'KATHERINE GISSELL','apellidos'=>'ORRALA SANCHEZ','correo'=>'katherine.orrala@pined.ec'],
			['nombres'=>'ARIANA MARISSA','apellidos'=>'TORRES ECHEVERRIA','correo'=>'ariana.torres@pined.ec'],
			['nombres'=>'LESLIE FIORELLA','apellidos'=>'BAYAS CHUCHUCA','correo'=>'leslie.bayas@pined.ec'],
			['nombres'=>'PAULA GABRIELA','apellidos'=>'CALDERON PINOARGOTE','correo'=>'paula.calderon@pined.ec'],
			['nombres'=>'ROMINA ALEJANDRA','apellidos'=>'DOMINGUEZ ARREAGA','correo'=>'romina.dominguez@pined.ec'],
			['nombres'=>'ANGEL PAUL','apellidos'=>'HARO ARAGUNDI','correo'=>'angel.haro@pined.ec'],
			['nombres'=>'AARON JOSTIN','apellidos'=>'ALVEAR ZAMBRANO','correo'=>'aaron.alvear@pined.ec'],
			['nombres'=>'LEYLAN IVETTE','apellidos'=>'GONZALEZ VACA','correo'=>'leylan.gonzalez@pined.ec'],
			['nombres'=>'MAURO FERNANDO','apellidos'=>'VEGA JACOME','correo'=>'mauro.vega@pined.ec'],
			['nombres'=>'ANTHONNY ALEXANDER','apellidos'=>'CRUZ ARANA','correo'=>'anthony.cruz@pined.ec'],
			['nombres'=>'SANYI STEFANIA','apellidos'=>'ARANA SANTANA','correo'=>'sanyi.arana@pined.ec'],
			['nombres'=>'JENNIFFER ADRIANA','apellidos'=>'CANDELARIO BARRAZUETA','correo'=>'jenniffer.candelario@pined.ec'],
			['nombres'=>'TAMARA IVANNA','apellidos'=>'LARREA BERZOSA','correo'=>'tamara.larrea@pined.ec'],
			['nombres'=>'CAMILA AMELL','apellidos'=>'ZEA BATIOJA','correo'=>'camila.zea@pined.ec'],
			['nombres'=>'MARIA BELEN','apellidos'=>'ALVAREZ AGUILAR','correo'=>'mariab.alvarez@pined.ec'],
			['nombres'=>'JUAN JOSE','apellidos'=>'GUERRERO CHANG','correo'=>'juan.guerrerochang@pined.ec'],
			['nombres'=>'MARIA ELENA','apellidos'=>'MONTESDEOCA MENA','correo'=>'maria.montesdeoca@pined.ec'],
			['nombres'=>'BRUNO MATIAS','apellidos'=>'QUIÑONEZ PARRA','correo'=>'bruno.quinonez@pined.ec'],
			['nombres'=>'MARIA ANGELICA','apellidos'=>'ANCHUNDIA DONOSO','correo'=>'maria.anchundia@pined.ec'],
			['nombres'=>'RICARDO ANDRES','apellidos'=>'CANESSA CAMPOVERDE','correo'=>'ricardo.canessa@pined.ec'],
			['nombres'=>'MICHAEL FERNANDO','apellidos'=>'MORAN AVILES','correo'=>'michael.moran@pined.ec'],
			['nombres'=>'LEONARDO JOSE','apellidos'=>'MOSCOSO SUAREZ','correo'=>'leonardo.moscoso@pined.ec'],
			['nombres'=>'LESLIE NOEMI','apellidos'=>'PEREZ GONZALEZ','correo'=>'leslie.perez@pined.ec'],
			['nombres'=>'MARIA PAULA','apellidos'=>'REYES ZAPATA','correo'=>'maria.reyes@pined.ec'],
			['nombres'=>'DANIEL ALEJANDRO','apellidos'=>'RONQUILLO SALGADO','correo'=>'daniel.ronquillo@pined.ec'],
			['nombres'=>'CARLOS ANDRES','apellidos'=>'SORIANO SUAREZ','correo'=>'carlos.soriano@pined.ec'],
			['nombres'=>'SAMUEL ANDRES','apellidos'=>'TORRES SALVATIERRA','correo'=>'samuel.torres@pined.ec'],
			['nombres'=>'DALIA VALENTINA','apellidos'=>'ZAMBRANO NEIRA','correo'=>'dalia.zambrano@pined.ec'],
			['nombres'=>'ALBERTO ALEXANDER','apellidos'=>'ALDAS DONOSO','correo'=>'alberto.aldas@pined.ec'],
			['nombres'=>'MARIA AUGUSTA','apellidos'=>'MENDEZ PASTOR','correo'=>'augusta.mendez@pined.ec'],
			['nombres'=>'ILIANA LILISBETH','apellidos'=>'MEJIA CASTRO','correo'=>'iliana.mejia@pined.ec'],
			['nombres'=>'CAMILA LISBETH','apellidos'=>'CASTILLO FLORES','correo'=>'camila.castillo@pined.ec'],
			['nombres'=>'NICOLAS FRANCISCO','apellidos'=>'PARRA  RIVADENEIRA','correo'=>'nicolas.parra@pined.ec'],
			['nombres'=>'YU MEI YANIRE','apellidos'=>'ALVAREZ BARRAGAN','correo'=>'yumei.alvarez@pined.ec'],
			['nombres'=>'OSWALDO ANDRES','apellidos'=>'MERA MUÑOZ','correo'=>'oswaldo.mera@pined.ec'],
			['nombres'=>'WALTER FRANCISCO','apellidos'=>'TAMAYO BENITES','correo'=>'walter.tamayo@pined.ec'],
			['nombres'=>'DANIEL ANDRES','apellidos'=>'ALVAREZ MARIÑO','correo'=>'daniel.alvarez@pined.ec'],
			['nombres'=>'LUIS MAURICIO','apellidos'=>'ARIAS MUÑOZ','correo'=>'luis.arias@pined.ec'],
			['nombres'=>'PATRICK JOSE','apellidos'=>'GAVILANES VECILLA','correo'=>'patrick.gavilanes@pined.ec'],
			['nombres'=>'JEA YONG ANDRES','apellidos'=>'HA GAVILANES','correo'=>'jeayong.ha@pined.ec'],
			['nombres'=>'JEA UN JOSSUE','apellidos'=>'HA ROMERO','correo'=>'jeaun.ha@pined.ec'],
			['nombres'=>'ROBERTO ISAAC','apellidos'=>'ALVAREZ IDROVO','correo'=>'roberto.alvarez@pined.ec'],
			['nombres'=>'ALEX XAVIER','apellidos'=>'CASTILLO FLORES','correo'=>'alex.castillo@pined.ec'],
			['nombres'=>'MIRIAN DANIELA','apellidos'=>'GUAMAN GALAN','correo'=>'mirian.guaman@pined.ec'],
			['nombres'=>'MARCOS FRANCISCO','apellidos'=>'PARRA RIVADENEIRA','correo'=>'marcos.parra@pined.ec'],
			['nombres'=>'LESLIE TAMARA','apellidos'=>'SALAZAR VELASQUEZ','correo'=>'leslie.salazar@pined.ec'],
			['nombres'=>'DANIELA ALEJANDRA','apellidos'=>'TAYLOR LUCAS','correo'=>'daniela.taylor@pined.ec'],
			['nombres'=>'EMILIO XAVIER','apellidos'=>'MORLA MUÑOZ','correo'=>'emilio.morla@pined.ec'],
			['nombres'=>'JESUS DAVID','apellidos'=>'SOLORZANO LOPEZ','correo'=>'jesus.solorzano@pined.ec'],
			['nombres'=>'JORGE XAVIER','apellidos'=>'RODRIGUEZ ZARATE','correo'=>'xavier.rodriguez@pined.ec'],
			['nombres'=>'GABRIELA ADALIA','apellidos'=>'PICO VERZOZA','correo'=>'gabriela.pico@pined.ec'],
			['nombres'=>'DANIEL FRANCISCO','apellidos'=>'CASTRO VELEZ','correo'=>'daniel.castro@pined.ec']
        );
		
		$students = Student2::all();
		$count = 0;
		foreach ($users as $user ) {
			//print($user['correo']);
			$count++;
			foreach ($students as $student) {
				if($student->nombres==$user['nombres'] && $student->apellidos==$user['apellidos'] && $student->matricula=="Ordinaria"){
					$perfil = Administrative::find($student->idProfile);
					$usuario = Usuario::find($perfil->userid);
					
					echo $count."_"."id:".$student->id."_idProfile".$student->idProfile." ".$user['correo']."CORREO:".$perfil->correo."			";
					//Actualización de correo en users_profile
					$perfil->correo=$user['correo'];
					$perfil->save();
					//Actualización de correo en users
					$usuario->email=$user['correo'];
					$usuario->save();
				}
			}

		}
    }
}
