<?php

use Illuminate\Database\Seeder;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel as Sentinel;

class RepresentantesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = array(
		    array('CESAR STALIN', 'ARELLANO VELASQUEZ', 'Masculino', 'cesararellano2013@gmail.com', '0999070785', '', 'Guayaquil', '', 'Representante'),
		    array('GABRIELA IBETH', 'MOREIRA  LOPEZ', 'Femenino', 'ibeth.moreiralopez@gmail.com', '0982024244', '', 'SAUCES VI MZ 351 VILLA 18', '042967982', 'Representante'),
		    array('EVELIN PAOLA', 'PEREZ CASTILLO', 'Femenino', 'merco-evelin@hotmail.es', '0988226397', '', 'vergeles mz 35a sl.39', '2019210', 'Representante'),
		    array('MARIA PIEDAD', 'SANCHEZ REYNA', 'Femenino', 'mariapiedadsanchez2018@hotmail.com', '0994821700', '', '', '', 'Representante'),
		    array('ANIBAL ALBERTO', 'BOLAÑOS MARTINEZ', 'Masculino', 'lorenacarvajal1601@gmail.com', '0996348715', '', 'La Joya Diamante Mz.1 v.35', '0993164215', 'Representante'),
		    array('MARIA FERNANDA', 'RUGEL RAMIREZ', 'Femenino', 'marife-84@hotmail.com', '0985908126', '', '', '', 'Representante'),
		    array('RAISSA ROMINA', 'MORA GORDILLO', 'Femenino', 'romy-17@hotmail.com', '', '', '', '', 'Representante'),
		    array('SUSANA MAGDALENA', 'MOSQUERA JIMENEZ', 'Femenino', 'susanamosquera6@gmail.com', '0999999999', '', '', '', 'Representante'),
		    array('DARA ANGELICA', 'TAYLOR LUCAS', 'Femenino', 'angelicataylor-86@hotmail.es', '', '', '', '', 'Representante'),
		    array('NADIA ALEXANDRA', 'QUIMI LOOR', 'Femenino', 'nadiamile1@gmail.com', '0992184766', '', 'GUAYACANES MZ. 117 A VILLA 5', '', 'Representante'),
		    array('ILIANA KATHIUSCA', 'SANTANA ALCIVAR', 'Femenino', 'isantana0391@gmail.com', '0998904402', '', 'Sauces 4 Bloque 42 Dpto. 203', '2217880', 'Representante'),
		    array('VANESSA ALEXANDRA', 'SEVILLA NAZARENO', 'Femenino', 'vsevilla_19@hotmail.com', '0993003629', '', 'URB. PARAISO DEL RIO 1 MZ 2714 VILLA 11', '3885614', 'Representante'),
		    array('DIANA STEFANIA', 'MARTINEZ REYES', 'Femenino', 'martinezreyesdiana@gmail.com', '0939449168', '', 'Guayacanes Mz. 30  V. 8', '042825637', 'Representante'),
		    array('JEANINE', 'JACOME CEVALLOS', 'Femenino', 'jeani_1987@hotmail.com', '0967855309', '', 'sauces 4 Mz. 375 V. 45', '042621417', 'Representante'),
		    array('MICHELLE KATHERINE', 'SANCHEZ GOMEZ', 'Femenino', 'michellsanchez19@hotmail.com', '', '', '', '', 'Representante'),
		    array('ALEXANDRA ELIZABETH', 'ROMERO JIMENEZ', 'Femenino', 'aleromero1@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA FERNANDA', 'VILLACRES ESPINAR', 'Femenino', 'mafer.villacres@gmail.com', '0997017206', '', 'La Joya Et Diamante', '2827919', 'Representante'),
		    array('STEFANIE GABRIELA', 'ALVAREZ ARREAGA', 'Femenino', 'stefanie_alvarez89@hotmail.com', '0982923777', '', 'CDLA. GUAYACANES MZ 213 VILLA 6', '042826104', 'Representante'),
		    array('KATTY ELIZABETH', 'TALLEDO LEON', 'Femenino', 'kattyelitorres@gmail.com', '0990204261', '', '', '', 'Representante'),
		    array('FRANKLIN AGUSTIN', 'VELEZ VELEZ', 'Femenino', 'vfranklin18@hotmail.com', '', '', '', '', 'Representante'),
		    array('EVELYN CAROLINA', 'GUZHÑAY ORTEGA', 'Femenino', 'evebell25@hotmail.com', '0984859184', '', 'Urbanización la Romareda etapa 4 mz1959 villa 14', '', 'Representante'),
		    array('MARIA CRISTINA', 'RUILOVA MOSQUERA', 'Femenino', 'marycris756@hotmail.com', '', '', '', '', 'Representante'),
		    array('JOSE MIGUEL', 'GUALPA LEMA', 'Femenino', 'jgualpa@conecel.com.ec', '', '', '', '', 'Representante'),
		    array('KAREN KATIUSKA', 'SABANDO MALDONADO', 'Femenino', 'karensabandomaldonado@hotmail.com', '0998511778', '', 'KM 13 1/2 VIA A LA COSTA URB. TERRANOSTRA ETAPA MALLORCA MZ 1294 V4', '046037843', 'Representante'),
		    array('MARIA ISABEL', 'SANCHEZ MIRANDA', 'Femenino', 'm_isabel_sanchez@yahoo.com', '', '', '', '', 'Representante'),
		    array('LUIS ALBERTO', 'JARA TOMALA', 'Femenino', 'ljara@bancoamazonas.com', '0992039933', '', '', '', 'Representante'),
		    array('RAPHAEL WILFRIDO', 'MORENO CRESPO', 'Femenino', 'morenocrespr@gmail.com', '', '', '', '', 'Representante'),
		    array('TATIANA MARINA', 'LOPEZ ANDRADE', 'Femenino', 'marina10843@hotmail.com', '0996507020', '', 'CDLA ABEL GILBERT 3 MZ A 13 VILLA 4', '042552121', 'Representante'),
		    array('AMY THALIA', 'SARMIENTO CARRERA', 'Femenino', 'a.sarmiento.carrera@hotmail.com', '', '', 'COLON 2005 Y LOS RIOS', '042193954', 'Representante'),
		    array('LISSETTE GISSELLA', 'MERO NOVELO', 'Femenino', 'lissettemero@hotmail.com', '0985746348', '', '', '', 'Representante'),
		    array('LISSETT FERNANDA', 'RONQUILLO VILLAGOMEZ', 'Femenino', 'lissett_ronquillo@hotmail.com', '', '', '', '', 'Representante'),
		    array('JOHN DAVE', 'VELEZ TERAN', 'Femenino', 'john_skate_93@hotmail.com', '', '', '', '', 'Representante'),
		    array('ANDREA STEPHANIE', 'PAREDES RAMOS', 'Femenino', 'andreaparedes7@gmail.com', '', '', '', '', 'Representante'),
		    array('LEONARDO VICENTE', 'ANDRADE CALDERON', 'Femenino', 'landradecalderon@outlook.com', '', '', 'Sauces 4', '5016472', 'Representante'),
		    array('GRACE ALEXANDRA', 'GELLIBERT MERCHAN', 'Femenino', 'gracegeme_04@hotmail.com', '0991065111', '', 'Metropolis 2E mz 1366 villa 2', '', 'Representante'),
		    array('LORENA HERMINIA', 'ONOFRE COELLO', 'Femenino', 'lorenaonofrecoello@gmail.com', '0999999999', '', '', '', 'Representante'),
		    array('GUSTAVO ANDRES', 'CIRES MOYA', 'Femenino', 'gcires@gmail.com', '', '', '', '', 'Representante'),
		    array('CAROLINA ALEJANDRA', 'SANCHEZ GARCIA', 'Femenino', 'karitop.beiiqp2@gmail.com', '', '', '', '', 'Representante'),
		    array('JOSE FRANCISCO', 'LEMA CAJILEMA', 'Masculino', 'lemafrancisco57@hotmail.com', '0939686147', '', '', '', 'Representante'),
		    array('GINGER TAMARA', 'DELGADO CASTILLO', 'Femenino', 'tamaradelgado1977@hotmail.com', '0980709348', '', '', '2827880', 'Representante'),
		    array('WENDY NATALIA', 'VALLEJO  CACHOTE', 'Femenino', 'wendy.vallejoc@hotmail.com', '', '', '', '', 'Representante'),
		    array('ALICIA MERCEDES', 'ZAMBRANO  MACIAS', 'Femenino', 'aliciagataz@hotmail.com', '0994677884', '', '', '', 'Representante'),
		    array('KATIUSKA ALEXANDRA', 'VALENCIA IZQUIETA', 'Femenino', 'gatita_2325@hotmail.com', '', '', '', '', 'Representante'),
		    array('INGELLISIE PAMELA', 'MENDEZ MEDRANO', 'Femenino', 'inge_pamelita@hotmail.com', '', '', '', '', 'Representante'),
		    array('JULISSA KATIUSKA', 'VERA ESPIN', 'Femenino', 'julissavera@hotmail.com', '0991502859', '', 'METROPOLIS 2B MZ. 1014 VILLA 33', '046016185', 'Representante'),
		    array('JESENIA ELVIA', 'SANTILLAN LOOR', 'Femenino', 'JesiSanLor@gmail.com', '0994736177', '', '', '', 'Representante'),
		    array('RAQUEL VANEZA', 'MOSQUERA AREVALO', 'Femenino', 'vaneza36@yahoo.com', '0992553209', '', 'urb. jardines del rio mz 23 villa 13', '044547292', 'Representante'),
		    array('EULALIA MARGARITA', 'SECAIRA TORO', 'Femenino', 'maggy2012bellaneira@hotmail.es', '', '', '', '', 'Representante'),
		    array('JESSICA VIRGINIA', 'BARROS SALDAÑA', 'Femenino', 'jessybrili@hotmail.com', '0983343433', '', 'Cdla. Cóndor Mz  F  Villa  32', '042127047', 'Representante'),
		    array('ERICKA SOFIA', 'GAMAZO ALVAREZ', 'Femenino', 'erickagamazo@hotmail.com', '0969390353', '', 'Cdla. Guayacanes Mz.113 villa 13', '042821157', 'Representante'),
		    array('AREANA LISETTE', 'VERA MONTESDEOCA', 'Femenino', 'arlivemo89@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('LINA DE LAS MERCEDES ', 'FRANCO CABEZAS', 'Femenino', 'diosconmigo115@hotmail.com', '', '', '', '', 'Representante'),
		    array('ELSY ALFARINA', 'OTERO SEGURA', 'Femenino', 'oteroelsy@gmail.com', '0999999999', '', '', '', 'Representante'),
		    array('ANNIE PRISCILA', 'RUIZ SANTANA', 'Femenino', 'kalos_k2@hotmail.com', '', '', '', '', 'Representante'),
		    array('KATIUSKA ELIZABETH', 'GARCIA REYES', 'Femenino', 'eliza2224@hotmail.com', '', '', '', '', 'Representante'),
		    array('CAROLINA GABRIELA', 'MORALES APOLO', 'Femenino', 'cmorales2901@gmail.com', '0991527132', '', 'Samanes 1 Mz: 121 Villa:5', '2219676', 'Representante'),
		    array('MARINA NARCISA', 'SALINAS ALMEA', 'Femenino', 'MARILYN1332@HOTMAIL.COM', '', '', '', '', 'Representante'),
		    array('LILIANA LISBETH', 'LEON LUCAS', 'Femenino', 'liliana_leonlucas@hotmail.com', '0994377816', '', 'Acuarela del Río mz46 vill25', '0994377816', 'Representante'),
		    array('LISPAO', 'CACERES MARTILLO', 'Femenino', 'lpcaceres.m@gmail.com', '0992735901', '', 'Martha de Roldos', '', 'Representante'),
		    array('GISELLA NATALY', 'BARCIA CORDOVA', 'Femenino', 'gisenataly_87@hotmail.com', '0982265237', '', 'MUCHO LOTE 2 PLAZA VICTORIA MZ 2917 V. 07', '044545488', 'Representante'),
		    array('MATILDE LASTENIA', 'RODRIGUEZ GONZALEZ', 'Femenino', 'mattylastenia@yahoo.es', '', '', '', '', 'Representante'),
		    array('MARTHA PAOLA', 'PAVON CARDENAS', 'Femenino', 'mpaolapavon1979@gmail.com', '', '', '', '', 'Representante'),
		    array('CARLOS HUMBERTO', 'ARAUJO PEREZ', 'Masculino', 'caraujop87@gmail.com', '0999999999', '', '', '', 'Representante'),
		    array('MARTHA MARYURI', 'ROMERO INTRIAGO', 'Femenino', 'jzambrano1280@hotmail.com', '', '', '', '', 'Representante'),
		    array('NELLY YADIRA', 'CARPIO RIVERA', 'Femenino', 'yadira.carpio@gmail.com', '', '', '', '', 'Representante'),
		    array('LADY YULIANA', 'QUEZADA VALAREZO', 'Femenino', 'layuli_1@hotmail.com', '', '', '', '', 'Representante'),
		    array('HERNEY JHOFRE', 'DELGADO ORDOÑEZ', 'Femenino', 'hjodelgado@gmail.com', '', '', '', '', 'Representante'),
		    array('OSCAR EUSEBIO', 'ENRIQUEZ IMBAQUINGO', 'Femenino', 'oei_66@yahoo.es', '0993968127', '', '', '', 'Representante'),
		    array('CRISTIAN ARISTOTELES', 'GONZALEZ  JIMENEZ', 'Femenino', 'cristiangonjin@hotmail.com', '0993385223', '', 'Metropolis 2 etapa E MZ1368  villa 40', '044633360', 'Representante'),
		    array('SANDRA JESSENIA', 'REYES CAMPUZANO', 'Femenino', 'sandrytjess@hotmail.com', '0984331082', '', '', '', 'Representante'),
		    array('OSWALDO FABRICIO', 'JIMENEZ LOPEZ', 'Femenino', 'fabojim83@gmail.com', '0991733519', '', '', '043077354', 'Representante'),
		    array('KATHERYN KRISTEL', 'POZO VILLEGAS', 'Femenino', 'katherynpozo@gmail.com', '0983379150', '', 'Samanes 5', '0983379150', 'Representante'),
		    array('CAROLA ERIKA', 'CEREZO CARRASCO', 'Femenino', 'carolita_piscis@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('DANIELA ISABEL', 'MENDOZA  BARAHONA', 'Femenino', 'gabyfpg@hotmail.com', '', '', '', '', 'Representante'),
		    array('ANDREA LUCRECIA', 'CEDEÑO ACOSTA', 'Femenino', 'acedeno81@hotmail.com', '0994898181', '', '', '', 'Representante'),
		    array('AMPARO DEL CARMEN ', 'SANTILLAN SAMANIEGO', 'Femenino', 'sincorreo6@hotmail.com', '', '', '', '', 'Representante'),
		    array('MAGALI YAMILE', 'QUEVEDO SAAVEDRA', 'Femenino', 'yami_qs@hotmail.com', '0986703303', '', '', '', 'Representante'),
		    array('JOSELIN DAYANA', 'LLAGUNO INTRIAGO', 'Femenino', 'dayanallaguno7@gmail.com', '0990852795', '', 'Cdla. Huancavilca Norte Mz b V108', '0990852795-0997415889-0980518709', 'Representante'),
		    array('KRISTHEL PRISCILA', 'LOPEZ CHULLI', 'Femenino', 'cchulli1163@hotmail.com', '0994587822', '', '', '', 'Representante'),
		    array('ROXANA MARIELA', 'ROBLES CRUZ', 'Femenino', 'roxanamariela21@gmail.com', '', '', 'Sauces 6 mz278 v21', '966741', 'Representante'),
		    array('JOSE MANUEL', 'YUBAILLO YUNGAN', 'Femenino', 'yubaillojose78@hotmail.com', '', '', '', '', 'Representante'),
		    array('GISELLE ROCIO', 'ARMIJOS ANDA', 'Femenino', 'gisro_ar@hotmail.com', '0992098958', '', 'Vergeles II Etapa Mz 111 V. 5', '042026822', 'Representante'),
		    array('NIXON', 'ZAMBRANO CULMA', 'Femenino', 'Karinsa21@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('KAREN YAMEL', 'REAL GONZALEZ', 'Femenino', 'karen_realg@hotmail.com', '0960433300', '', 'sauces 5 mz 223 villa 5', '2827264', 'Representante'),
		    array('KATHERINE STEFANIA', 'MARTILLO PILAY', 'Femenino', 'kmartillopilay@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARTI RUPERTO', 'ALEJANDRO GAIBOR', 'Femenino', 'rupert_alejandro@yahoo.com', '', '', '', '', 'Representante'),
		    array('ROXANA VANESSA', 'FLORES SARMIENTO', 'Femenino', 'roxiflores_turismo@hotmail.com', '0996313179', '', 'Guayacanes, Mz. 94, Villa 20', '045108075', 'Representante'),
		    array('PRISCILA SOLEDAD', 'GALLARDO MORA', 'Femenino', 'priscilagallardom@hotmail.com', '0999575588', '', 'URB. Ciudad celeste etapa La Ria mz 4 villa 52', '042820473 - 046000797', 'Representante'),
		    array('VERONICA ZORAIDA', 'CRUZ SALAZAR', 'Femenino', 'verocruz13@hotmail.com', '', '', '', '', 'Representante'),
		    array('STEPHANIE MICHELLE', 'SARMIENTO CARRERA', 'Femenino', 'steph.s.carrera@gmail.com', '0960783836', '', '', '', 'Representante'),
		    array('JOSE MANUEL', 'BUSTAMANTE MORENO', 'Femenino', 'paola_oyola9@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('ASTRID STEPHANIE', 'CORDOVA POZO', 'Femenino', 'astrids_072@hotmail.com', '', '', '', '', 'Representante'),
		    array('CHEN', 'WEI', 'Femenino', '1404927723@qq.com', '', '', '', '', 'Representante'),
		    array('SHAN', 'DAI JIALI', 'Femenino', 'fufen9494@gmail.com', '', '', '', '', 'Representante'),
		    array('DIOGENES ENRIQUE', 'VASQUEZ RIERA', 'Femenino', 'evasquez@k-dobra.com', '', '', '', '', 'Representante'),
		    array('VANESSA VIVIANA', 'HIDALGO CEDEÑO', 'Femenino', 'dravhc@hotmail.com', '', '', '', '', 'Representante'),
		    array('ANA BEATRIZ', 'LIBERIO ZAMORA', 'Femenino', 'ana.liberio2018@hotmail.com', '0990462398', '', '', '', 'Representante'),
		    array('DARWIN MANUEL', 'ARANA BAJAÑA', 'Masculino', 'darwin.arana2018@hotmail.com', '0996403782', '', '', '', 'Representante'),
		    array('JORGE ULISES', 'MALDONADO UQUILLAS', 'Femenino', 'jorgemaldonadou@hotmail.com', '', '', '', '', 'Representante'),
		    array('JAN RICARDO', 'RENELLA CASTRO', 'Masculino', 'rosa@paydcargo.com.ec', '0999999999', '', '', '', 'Representante'),
		    array('PATRICIA TANIA', 'GALVEZ BRAVO', 'Femenino', 'sincorreo10@hotmail.com', '', '', '', '', 'Representante'),
		    array('EDGAR IVAN', 'SILVA BARRENO', 'Femenino', 'e.ivansilva.b@gmail.com', '', '', '', '', 'Representante'),
		    array('GILBERTH ENRIQUE', 'MORA AVILES', 'Femenino', 'enriquemoragema@hotmail.com', '', '', '', '', 'Representante'),
		    array('WALTER DANILO', 'ARANA BAJAÑA', 'Masculino', 'danilo.arana2018@hotmail.com', '0993083778', '', '', '', 'Representante'),
		    array('DAVID SAMUEL', 'VACA FRANCO', 'Femenino', 'gerencia_structech@hotmail.com', '', '', '', '', 'Representante'),
		    array('CELERINO JOSE', 'ARIAS QUEZADA', 'Femenino', 'oceanagro@outlook.es', '', '', '', '', 'Representante'),
		    array('LUIS ALFREDO', 'ROJAS BARAHONA', 'Femenino', 'alfffffff2106@hotmail.com', '', '', '', '', 'Representante'),
		    array('DANNY ALEJANDRO', 'BRAVO CHONG', 'Femenino', 'dbravochong@yahoo.com', '', '', '', '', 'Representante'),
		    array('ESTEFAN ROLANDO', 'ARCOS GOMEZ', 'Femenino', 'rarcos@corpfernandez.com', '0983801650', '', 'Huancavilca Norte Mz. D villa 13', '2182776', 'Representante'),
		    array('CESAR DANILO', 'CAMACHO GAVILANEZ', 'Femenino', 'dacamacho_74@yahoo.es', '', '', '', '', 'Representante'),
		    array('BETTY JULISSA', 'BARRAGAN ALVAREZ', 'Femenino', 'n5kkeyjul@hotmail.com', '', '', '', '', 'Representante'),
		    array('EMILIA MARIBEL', 'GUAMAN GALAN', 'Femenino', '2018-05-31', 'guamangalan20@hotmail.com', '', '', '', '', 'Representante'),
		    array('ANA MARIA', 'GALARZA INCHIGLEMA', 'Femenino', 'ericka-cali20@hotmail.com', '', '', '', '', 'Representante'),
		    array('LUIS EDELBERTO', 'MOYON GADUAY', 'Femenino', 'luis-moyon@hotmail.com', '', '', '', '', 'Representante'),
		    array('FAVIANNA', 'PAUCAR TAMBO', 'Femenino', 'lindassomostodas@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('XIMENA', 'PARRAGA LEMA', 'Femenino', 'sincorreo13@hotmail.com', '', '', '', '', 'Representante'),
		    array('ANGEL MARIA', 'CHINLLI SAEZ', 'Femenino', 'angel.24marzo@gmail.com', '', '', '', '', 'Representante'),
		    array('CARLOS IVAN', 'MANRIQUE  GUERRERO', 'Femenino', 'distribuidoradetextosgr@hotmail.com', '', '', '', '', 'Representante'),
		    array('TANYA IVONNE', 'SALVATIERRA VANEGAS', 'Femenino', '2018-06-13', 'tanyaivonnesalvatierravanegas@hotmail.com', '', '', '', '', 'Representante'),
		    array('GLENDA LETICIA', 'AVILES CORTAZAR', 'Femenino', 'glendaaviles123@hotmail.com', '', '', '', '', 'Representante'),
		    array('ETTY MARY', 'ECHEVERRIA GARCIA', 'Femenino', 'ettymar@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARTINA PERPETUA', 'SALTOS PLACENCIO', 'Femenino', 'msaltosplacencio@hotmail.com', '0995126162', '', 'Etapa 6 Mucho Lote mz 2577  v4', '6622721', 'Representante'),
		    array('NARCISA DE JESUS', 'APOLO LOPEZ', 'Femenino', 'narcisaapolo@hotmail.com', '0998169780', '', 'Samanes 1 Mz: 121 Villa:5', '042219676', 'Representante'),
		    array('IVO JAVIER', 'JARAMILLO REYES', 'Femenino', 'ivoxavierj@hotmail.com', '0998985901', '', 'LA RIOJA ETAPA ASTURIAS MZ 8 VILLA 28', '4507054', 'Representante'),
		    array('IRENE DEL CISNE', 'ZAPATA RAMIREZ', 'Femenino', 'irenezapata72@hotmail.com', '0989616334', '', '', '', 'Representante'),
		    array('MARIA AUGUSTA', 'PASTOR ROMERO', 'Femenino', 'm.agu76@hotmail.com', '', '', '', '', 'Representante'),
		    array('GILDO SALVADOR', 'VELIZ ALCIVAR', 'Masculino', 'gildova_256@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('MAGALY JOSEFINA', 'MALDONADO ORDOÑEZ', 'Femenino', 'mag_2003@hotmail.com', '', '', '', '', 'Representante'),
		    array('JUAN ANTONIO', 'NAVARRO NAVARRO', 'Femenino', '2018-06-06', 'mariuxi893@hotmail.com', '', '', '', '', 'Representante'),
		    array('HENRY MANUEL', 'ESPINOZA ESPINOZA', 'Femenino', 'ing.hee@hotmail.com', '', '', '', '', 'Representante'),
		    array('JOHNNY GERARDO', 'ALVAREZ JARA', 'Femenino', 'johnnyal1@hotmail.com', '0988266121', '', '', '', 'Representante'),
		    array('CHRISTIAN DAVID', 'POVEDA VELEZ', 'Femenino', 'gj03043@gmail.com', '', '', '', '', 'Representante'),
		    array('ROMMEL EUDORO', 'MORALES MURILLO', 'Masculino', '2018-06-15', 'rommelt1000@gmail.com', '0990928383', '', 'Urbanización La Joya Etapa Tiara mz 10 v 40', '044507739', 'Representante'),
		    array('OSWALDO HORACIO', 'MERA MACIAS', 'Femenino', 'meraoswaldo@hotmail.com', '0999533968', '', '', '', 'Representante'),
		    array('WILSON ANTONI', 'FU LOQUI', 'Masculino', 'chiquitina1907@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('MARIA NEREYCE', 'GANCHOZO ANDRADE', 'Femenino', 'mariaganchozo@outlook.com', '0968953353', '', '', '', 'Representante'),
		    array('MIRNA BENJAMINA', 'BALLESTEROS SOL', 'Femenino', '2018-06-21', 'eabravo@espol.edu.ec', '', '', '', '', 'Representante'),
		    array('JAVIER RAMIRO', 'SUANGO CABRERA', 'Femenino', 'javiercito_gye_1976@yahoo.com', '0990335367', '', 'CDLA. GUAYACANES MZ. 114 VILLA 17', '2822638', 'Representante'),
		    array('MARIA ESTEFANIA', 'FEIJOO MORALES', 'Femenino', 'miafeijoo.91@gmail.com', '0981326929', '', '', '', 'Representante'),
		    array('RUTH ELIZABETH', 'MENDIETA REYES', 'Femenino', 'ruth.mendieta@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA BURGOS', 'BURGOS ANDRADE', 'Femenino', 'mburgosandrade@hotmail.com', '', '', '', '', 'Representante'),
		    array('JIMMY MAURICIO', 'QUINDE PONTON', 'Femenino', 'jimmyieugenia@hotmail.es', '', '', '', '', 'Representante'),
		    array('HILDA CONCHITA', 'GRIJALVA ARRIAGA', 'Femenino', 'hildagrijalva@hotmail.com', '', '', '', '', 'Representante'),
		    array('LUZ MARINA MARJORIE ', 'AVILES SOTOMAYOR', 'Femenino', 'marjorie_aviles@hotmail.com', '', '', '', '', 'Representante'),
		    array('ROSA AMELIA', 'BONILLA VIZUETA', 'Femenino', 'ambovi1962@hotmil.com', '', '', '', '', 'Representante'),
		    array('JUANA LETICIA', 'FRERE FRANCO', 'Femenino', 'jfrerefranco@hotmail.com', '', '', '', '', 'Representante'),
		    array('NORMA ELOISA', 'AYALA ORELLANA', 'Femenino', 'norayala1@hotmail.com', '', '', '', '', 'Representante'),
		    array('ANA DEL ROCIO', 'ZAMBRANO MIÑO', 'Femenino', 'anaroci_zambrano26@hotmail.com', '0993124492', '', '', '', 'Representante'),
		    array('JORGE ALFREDO', 'MALDONADO ASENCIO', 'Femenino', 'jorgeasencio2002@gmail.com', '', '', '', '', 'Representante'),
		    array('CARLOS ROBERTO', 'ALVAREZ VITORES', 'Femenino', 'crobertito@hotmail.com', '0992040132', '', '', '', 'Representante'),
		    array('ROSA AMERICA', 'LOZANO RUIZ', 'Femenino', 'andyyrose999@gmail.com', '0999999999', '', '', '', 'Representante'),
		    array('ILIANA CELESTE', 'MIÑO RIVERO', 'Femenino', 'celeste.mino@hotmail.com', '', '', '', '', 'Representante'),
		    array('JANETH', 'ANZULES MACIAS', 'Femenino', 'sincorreo22@hotmail.com', '', '', '', '', 'Representante'),
		    array('JEANETT DEL ROCIO', 'MORAN ORTIZ', 'Femenino', 'janet.moran.ortiz@gmail.com', '0999999999', '', '', '', 'Representante'),
		    array('MARTHA', 'BRACHO OLAYA', 'Femenino', 'martha_bracho@hotmail.com', '0999036936', '', 'SAMANES 4 MZ. 404 VILLA 30', '042213956', 'Representante'),
		    array('RUBI PATRICIA', 'HUANCAYO RIVAS', 'Femenino', 'wcevallos2007@hotmail.com', '0999898032', '', 'Celda. Guayacsnez MZ 226 V 22', '2822490', 'Representante'),
		    array('MARIANA MINERVA', 'DELGADO SANTOS', 'Femenino', 'm3delsa@hotmail.es', '0999999999', '', '', '', 'Representante'),
		    array('CARLOS RAMIRO', 'CORDERO CORDERO', 'Femenino', 'carcordero16@gmail.com', '', '', '', '', 'Representante'),
		    array('MARIA ELENA', 'CRIOLLO LOOR', 'Femenino', 'maele-69@hotmail.com', '', '', '', '', 'Representante'),
		    array('DENISSE PAOLA', 'ANDRADE VARGAS', 'Femenino', 'pao-89-andrade@hotmail.com', '', '', '', '', 'Representante'),
		    array('JORGE ANTONIO', 'CEDEÑO ASPIAZU', 'Femenino', 'jcedeno@redsis.net.ec', '0994173035', '', 'URB. PAJARO AZUL MZ G4 VILLA 5', '2041027', 'Representante'),
		    array('MANUEL ENRIQUE', 'ZUÑIGA SEGARRA', 'Femenino', '2018-06-07', 'lorenamaria.av_0412@hotmail.com', '0990735167', '', 'Guayacanes mz 19 villa 14', '042824428', 'Representante'),
		    array('CECILIA VICTORIA', 'FLORES BALON', 'Femenino', 'ceciflores95@hotmail.com', '', '', '', '', 'Representante'),
		    array('DELIA DEL CARMEN', 'CRIOLLO COROZO', 'Femenino', 'dcriollo.64@gmail.com', '', '', '', '', 'Representante'),
		    array('GEORGINA NARCISA', 'OCEJO CHERREZ', 'Femenino', 'byron@hotmail.com', '', '', '', '', 'Representante'),
		    array('DIOSDADO WELLINGTON', 'CARPIO MAYOR', 'Femenino', 'diosdado57@hotmail.com', '0999002283', '', 'Cdla orquídeas', '042980379', 'Representante'),
		    array('BERNARDO LUDGARDO', 'OCHOA MORALES', 'Femenino', 'bernardo8amorales@hotmail.com', '0981534596', '', '', '', 'Representante'),
		    array('CARMEN SOFIA', 'REYES LOPEZ', 'Femenino', 'carmensofia0611@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('JANETH MARGARITA', 'ORTIZ TORAL', 'Femenino', 'janemar58@gmail.com', '', '', '', '', 'Representante'),
		    array('YOLANDA JACQUELINE', 'SANCHEZ CABRITONGO', 'Femenino', 'jsanchezc97@gmail.com', '0999382732', '', 'Cdla. Las Orquideas Mz 51 Villa 49', '042892705', 'Representante'),
		    array('PATRICIA EMILY', 'VELIZ FIGUEROA', 'Femenino', 'reinapatty1@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('CRISTOBAL ORLANDO', 'PILLASAGUA GUERRA', 'Femenino', 'asesorempresarial.cpillasagua@gmail.com', '', '', '', '', 'Representante'),
		    array('CYNTHIA HANNELORE', 'VERA CEPEDA', 'Femenino', 'hannelore68@hotmail.com', '0999553286', '', 'Alborada 8ava. Etapa Mz. 846 Villa 5', '5127977    2232537', 'Representante'),
		    array('KETTY ALEXANDRA', 'GUIM CONTRERAS', 'Femenino', 'kguim@kcc.com', '', '', '', '', 'Representante'),
		    array('ELSY GUADALUPE', 'CAMPAÑA  DAVILA', 'Femenino', 'elsy.campana@gmail.com', '', '', '', '', 'Representante'),
		    array('SHIRLEY JANET', 'CENTURION GUTIERREZ', 'Femenino', 'shijancengut@hotmail.com', '', '', '', '', 'Representante'),
		    array('IVAN FEDERICO', 'PLUAS AVILA', 'Femenino', 'i_federico@hotmail.com', '', '', '', '', 'Representante'),
		    array('YOLANDA VANESSA', 'MOSCOSO FERNANDEZ', 'Femenino', 'moscosovanessa@yahoomail.com', '', '', '', '', 'Representante'),
		    array('GINA ANGELA', 'LUCAS ALVARADO', 'Femenino', 'glukas1964@gmail.com', '0983840467', '', '', '', 'Representante'),
		    array('KARINA SORAYA', 'SOLARTE MORALES', 'Femenino', 'kaso1967@hotmail.es', '', '', '', '', 'Representante'),
		    array('JORGE DANILO', 'YEPEZ TRIANA', 'Femenino', 'daniloyepez45@hotmail.com', '', '', '', '', 'Representante'),
		    array('KETTY MARIANA', 'FRANCO SESME', 'Femenino', 'kfrancos2006@yahoo.es', '', '', '', '', 'Representante'),
		    array('JORGE LUIS', 'REYES MOLINA', 'Femenino', 'jorgeluisrm2007@hotmail.com', '', '', '', '', 'Representante'),
		    array('KELLY DORIS', 'BERZOSA VERGARA', 'Femenino', 'ed.larrea68@yahoo.com', '0999413375', '', '', '', 'Representante'),
		    array('GEORGINA', 'BARZOLA IRRAZABAL', 'Femenino', 'gina-barzola@hotmail.com', '0995553468', '', '', '', 'Representante'),
		    array('WALTER FRANCISCO', 'TAMAYO PINO', 'Femenino', 'walterftp@hotmail.com', '', '', '', '', 'Representante'),
		    array('BETTY PILAR', 'RUIZ VILLEGAS', 'Femenino', 'marianaruizv@hotmail.com', '', '', '', '', 'Representante'),
		    array('SARA GENOVEVA', 'CEDILLO HERNANDEZ', 'Femenino', 'dr.jimmy-vaccaro@hotmail.com', '', '', '', '', 'Representante'),
		    array('CRISTIAN WLADIMIR', 'CANTOS WALSH', 'Femenino', 'cristian.cantos@gmail.com', '0987082793', '', 'Samanes 7', '2210123', 'Representante'),
		    array('ZOILA VIRGINIA', 'VELASQUEZ RENDON', 'Femenino', 'zvelasquez-01@hotmail.es', '', '', '', '', 'Representante'),
		    array('ANGELICA MARIA', 'LABORDE GRANADOS', 'Femenino', 'angielaborde_38@hotmail.com', '', '', '', '', 'Representante'),
		    array('ELIZABETH AUXILIADORA', 'POTES YAGUAL', 'Femenino', 'ELIPOTES@HOTMAIL.COM', '0985974157', '', 'CDLA GUAYACANES MZ 121 VILLA 4', '042621341  Ó  045104290', 'Representante'),
		    array('YAZMIN DEL ROCIO', 'DURANGO CORDOVA', 'Femenino', 'yazmin_durango@hotmail.com', '0992044103', '', '', '', 'Representante'),
		    array('KARINA INES', 'ZAMORA ORDOÑEZ', 'Femenino', 'kizo2906@gmail.com', '0993793890', '', 'Sauces 3 Mz 136 V 22', '2572287', 'Representante'),
		    array('NURIA JUDITH', 'BOHORQUEZ CRUZ', 'Femenino', 'sincorreo27@hotmail.com', '', '', '', '', 'Representante'),
		    array('MAGALI ISABEL', 'POZO FRANCO', 'Femenino', 'maggipozo@yahoo.es', '0993504123', '', 'Samanes 2 Mz. 229 Villa 8', '2212174', 'Representante'),
		    array('POLY MARGARITA', 'IZURIETA COSTA', 'Femenino', 'pizurietac.2008@gmail.com', '0994885304', '', 'Mucho Lote 2 Mz 2911 zl 44', '4605950', 'Representante'),
		    array('SANDRA JENNIFFER', 'VALENCIA JAIME', 'Femenino', 'jenniffer2804@hotmail.es', '', '', '', '', 'Representante'),
		    array('WASHINGTON DECIO', 'RUIZ LEON', 'Femenino', 'ruizproyec@hotmail.com', '', '', '', '', 'Representante'),
		    array('ZULLY GUISELLA', 'ZAMBRANO MIÑO', 'Femenino', 'salvaarell@hotmail.com', '', '', '', '', 'Representante'),
		    array('RIGOBERTO JOSE', 'GUERRERO BRAVO', 'Femenino', 'rj-guerrero@hotmail.com', '', '', '', '', 'Representante'),
		    array('CARLOS AUGUSTO', 'MOTATO LOPEZ', 'Femenino', 'carlosmotato10@hotmail.com', '', '', '', '', 'Representante'),
		    array('PATRICIA ALEXANDRA', 'ANDRADE CEVALLOS', 'Femenino', 'andradepatricia@hotmail.com', '', '', '', '', 'Representante'),
		    array('LUPITA SOFIA', 'MUÑOZ MARTINEZ', 'Femenino', 'dome_ni@hotmail.es', '', '', '', '', 'Representante'),
		    array('ROCIO DEL CARMEN', 'SANCHEZ LARA', 'Femenino', 'chyoproducciones16@gmail.com', '', '', '', '', 'Representante'),
		    array('GINA ELIZABETH', 'MOSQUERA JARA', 'Femenino', 'gieliznf@gmail.com', '', '', '', '', 'Representante'),
		    array('PEDRO DE LA CRUZ', 'AVILA FRANCO', 'Masculino', 'pedroavilaf@hotmail.com', '0989720483', '', '', '', 'Representante'),
		    array('JESSENIA ELVIRA', 'DE LA TORRE GARCIA', 'Femenino', 'jessi0676@gmail.com', '0997992654', '', 'Cdla Guayacanes Mz 47 V 4', '04-2620120', 'Representante'),
		    array('EDGAR WALBERTO', 'JARAMILLO URGILES', 'Femenino', 'edgarjara74@hotmail.com', '', '', '', '', 'Representante'),
		    array('GUSTAVO FABRICIO', 'PAZMIÑO GORDILLO', 'Masculino', 'guspazgor@hotmail.com', '0981600106', '', '', '', 'Representante'),
		    array('EDDNA EUGENIA', 'PEÑAFIEL SARCOS', 'Femenino', 'eddnita_69@hotmail.com', '0991254362', '', '', '', 'Representante'),
		    array('ROGER RIDER', 'BURGOS CHICA', 'Femenino', 'rogers_burg@hotmail.com', '', '', '', '', 'Representante'),
		    array('SANDRA MARIUXI', 'GUZMAN  AVILES', 'Femenino', 'igualpa@conecel.com.ec', '', '', '', '', 'Representante'),
		    array('MERCEDES ELIZABETH', 'LIMA MACANCHI', 'Femenino', 'mercedeslim1@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('JORGE JOAQUIN', 'SERRANO VELEZ', 'Femenino', 'jorgeserrano.64@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('CECIBEL HERMELINDA', 'ALVAREZ SANTANA', 'Femenino', 'cecibelalvarez@hotmail.com', '', '', 'Sauces 8 mz.454 F-18 v-9', '2176750', 'Representante'),
		    array('MARIA SOLEDAD', 'GAVILANES ALARCON', 'Femenino', 'miran-hg@hotmail.com', '', '', '', '', 'Representante'),
		    array('CECILIA VERONICA', 'ALVARADO JARAMILLO', 'Femenino', 'ceciliadegarces@gmail.com', '0992356861', '', 'Guayacanes mz 235 villa8', '042823341', 'Representante'),
		    array('BETTY MARILU', 'BRAVO LOOR', 'Femenino', 'bettbrav@outlook.com', '0999999999', '', '', '', 'Representante'),
		    array('OMAYRA', 'MONTALVO MANZABA', 'Femenino', 'omairamontalvom@gmail.com', '', '', '', '', 'Representante'),
		    array('FRANCISCO GEOVANNI', 'AVILES JIMENEZ', 'Femenino', 'faviles359@gmail.com', '', '', '', '', 'Representante'),
		    array('MARJORIE MARICELA', 'VEGA SOLIS', 'Femenino', 'maryvegasolis@hotmail.es', '', '', '', '', 'Representante'),
		    array('ROSALVA EDITH', 'ARAGUNDI RODRIGUEZ', 'Femenino', 'rosar2524@hotmail.com', '0999388911', '', '', '', 'Representante'),
		    array('RICHARD PETER', 'ORRALA MOROCHO', 'Femenino', 'richardorrala69@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARICELA MARGARITA', 'MOSCOSO GALLEGOS', 'Femenino', 'mariceladesantos73@hotmail.com', '', '', '', '', 'Representante'),
		    array('GINA MARIBEL', 'PINCAY REYES', 'Femenino', 'gpincay@rolasa.com', '0999571211', '', '', '', 'Representante'),
		    array('EDDA ELIZABETH', 'CASTILLO SALVATIERRA', 'Femenino', 'elizacastillo0408@hotmail.com', '', '', '', '', 'Representante'),
		    array('ALLIZON JULISSA', 'SOLORZANO LOPEZ', 'Femenino', 'piratahermoso@yahoo.com', '', '', '', '', 'Representante'),
		    array('MARIA BRIGITTE', 'SEMPERTEGUI PESANTES', 'Femenino', 'bsempertegui@hotmail.com', '', '', '', '', 'Representante'),
		    array('JOSE PABLO', 'CHU LEE', 'Femenino', 'daniyulee@hotmail.com', '0994715536', '', 'Garzota 2 mz 64 v. 29', '0993020317', 'Representante'),
		    array('MARCOS ALEJANDRO', 'PARRA RAMBAY', 'Femenino', 'consultoriazamorano@gmail.com', '0979817046', '', 'Ciudadela Guayacanes Manzana 117 A Villa 7', '6051189', 'Representante'),
		    array('JANETH NATIVIDAD', 'GONZALEZ YAGUAL', 'Femenino', 'jara90210@hotmail.com', '', '', '', '', 'Representante'),
		    array('JOSE LUIS', 'VERA FIALLOS', 'Femenino', 'josevera_028@hotmail.com', '0996437303', '', '', '', 'Representante'),
		    array('MARCELA MARIELLA', 'MUÑOZ GUERRA', 'Femenino', 'karla_ruiz-292@hotmail.com', '', '', '', '', 'Representante'),
		    array('EUFEMIA CONSUELO', 'MONTOYA CAYAMBE', 'Femenino', 'monconsu2811@gmail.com', '', '', '', '', 'Representante'),
		    array('VICTOR FRANKLIN', 'LLANOS HERNANDEZ', 'Femenino', 'vfllh_58@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('CECILIA ELIZABETH', 'TAMAYO MERO', 'Femenino', 'cecitamayo50@gmail.com', '', '', '', '', 'Representante'),
		    array('SHIRLEY', 'MAYA BENAVIDES', 'Femenino', 'smaya670@gmail.com', '', '', '', '', 'Representante'),
		    array('JAVIER OMAR', 'MIRANDA CHELE', 'Femenino', 'jomir_1501@hotmail.com', '', '', '', '', 'Representante'),
		    array('JORGE DOUGLAS', 'RODRIGUEZ SELLERS', 'Femenino', 'j_rodrigus@hotmail.com', '0990314518', '', 'Cdla Guayacanes Mz 168 Villa 12', '0990314518', 'Representante'),
		    array('ITALIA MARIELA', 'CINO RUIZ', 'Femenino', 'marycino@hotmail.com', '0990311094', '', 'Cdla.Acuarela del Rio ; mz 27 solar 19', '', 'Representante'),
		    array('GABRIEL NARCIZO', 'AGUIRRE LAVAYEN', 'Femenino', 'aguirrejosue11@gmail.com', '', '', '', '', 'Representante'),
		    array('KATIANA ELIZABETH', 'CEDEÑO FREIRE', 'Femenino', 'rickyasotomayor@hotmail.es', '', '', '', '', 'Representante'),
		    array('JESSICA MARCIA', 'GARCIA PROAÑO', 'Femenino', 'sincorreo1@gmail.com', '', '', '', '', 'Representante'),
		    array('JOSE ALBERTO', 'GUAMAN BARBECHO', 'Femenino', 'jagb1778@gmail.com', '0986595237', '', 'Velasco Ibarra 3-17', '', 'Representante'),
		    array('MARTINA NARCISA', 'CASTRO CASTRO', 'Femenino', 'sincorreo2@gmail.com', '', '', '', '', 'Representante'),
		    array('ANA DEL ROCIO', 'MUÑOZ MERA', 'Femenino', 'anro-3@hotmail.com', '', '', '', '', 'Representante'),
		    array('LUZ MARINA', 'SUAREZ VERA', 'Femenino', 'luz.suarez@jrcpharma.com', '0997910709', '', 'Urbanización Villa Club Etapa Hermés Mz. 2 Villa 30', '2165477', 'Representante'),
		    array('GEORGINA DE LAS MERCEDES', 'VELEZ GERMAN', 'Femenino', 'ginayvalentina@hotmail.com', '', '', '', '', 'Representante'),
		    array('GLADYS  DEL PILAR', 'PESANTES BAJAÑA', 'Femenino', 'gladys_1405@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('ANA CAROLINA', 'MONROY GAVILANEZ', 'Femenino', 'anacarolinamonroygavilanez@yahoo.com', '', '', '', '', 'Representante'),
		    array('GINA DEL ROCIO', 'VERA CHAFLA', 'Femenino', 'anig1216@gmail.com', '', '', '', '', 'Representante'),
		    array('ELSA ALEXANDRA', 'MORAN TOMALA', 'Femenino', 'multiproductosmm@gmail.com', '', '', '', '', 'Representante'),
		    array('MAGALI ARACELI', 'SAA TOLOZANO', 'Femenino', 'magalysaa72@hotmail.com', '0969352065', '', '', '', 'Representante'),
		    array('MARJORIE YANETH', 'MONTOYA SOTOMAYOR', 'Femenino', 'MAYIMONT@HOTMAIL.COM', '0980690222', '', 'Ciudadela Guayacanes', '', 'Representante'),
		    array('FÁTIMA MARÍA', 'RIZO CARPIÓ', 'Femenino', 'fati_rizzo1410@hotmail.com', '0998054797', '', '', '', 'Representante'),
		    array('PATRICIA JACQUELINE', 'DELGADO LEON', 'Femenino', 'patyjacquelin@hotmail.com', '', '', '', '', 'Representante'),
		    array('RENE RODOLFO', 'RODAS SOTO', 'Femenino', 'rrodasctg@hotmail.com', '0969147533', '', 'GUAYACANES MZ 15 VILLA 5', '', 'Representante'),
		    array('HILDA MIRIAM', 'GUTIERREZ GOMEZ', 'Femenino', 'ab-paul-lude@hotmail.com', '', '', '', '', 'Representante'),
		    array('SUSANA RAQUEL', 'AGUIRRE GARCIA', 'Femenino', 'susana.r.aguirre@gmail.com', '', '', '', '', 'Representante'),
		    array('KATTY MONSERRAT', 'VACA ARAMBULO', 'Femenino', 'Kattyvaca2727@hotmail.com', '', '', '', '', 'Representante'),
		    array('MIRIAM NARCISA', 'TULCANAZA LAAZ', 'Femenino', 'miriam-inproduct@hotmail.com', '', '', '', '', 'Representante'),
		    array('ING. WENDY CECIBEL', 'SABANDO MALDONADO', 'Femenino', 'wn0503sabando@gmail.com', '0997509823', '2827714 array(ABUELOS)', '', '4546599', 'Representante'),
		    array('DELFINA VICTORIA', 'SILVA MORA', 'Femenino', 'sincorreo5@gmail.com', '', '', '', '', 'Representante'),
		    array('SHIRLEY', 'MERA SALA', 'Femenino', 'sincorreo6@gmail.com', '', '', '', '', 'Representante'),
		    array('ALINA JANETT', 'VELIZ BONE', 'Femenino', 'ali_spapeluqueria@hotmail.com', '', '', '', '', 'Representante'),
		    array('ALEXANDRA ELIZABETH', 'YEPEZ VERA', 'Femenino', 'alitaeliza@gmail.com', '0997433008', '', '', '', 'Representante'),
		    array('MERCEDES HERLINDA', 'LAMILLA SANCHEZ', 'Femenino', 'herlinda1972_@hotmail.com', '', '', '', '', 'Representante'),
		    array('CARLOS ALBERTO', 'RONQUILLO VARGAS', 'Femenino', 'cronquillo4670@gmail.com', '0996224103', '', '', '', 'Representante'),
		    array('JESSICA VERONICA', 'JARAMILLO SANTAMARIA', 'Femenino', 'josegermanchavezrodriguez@gmail.com', '', '', '', '', 'Representante'),
		    array('MILKA PATRICIA', 'ROBALINO ALVARADO', 'Femenino', 'parttyrobalino@gmail.com', '', '', '', '', 'Representante'),
		    array('LAURA MERCEDES', 'BAYAS SANCHEZ', 'Femenino', 'paupi2306@hotmail.com', '0995579449', '', '', '', 'Representante'),
		    array('MONICA JANINA', 'BATIOJA LEMOS', 'Femenino', 'ivetterosero@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARTHA IVONNE', 'VALENCIA ESTRADA', 'Femenino', 'mvalencia95@hotmail.com', '', '', '', '', 'Representante'),
		    array('VERONICA CECILIA', 'JORDAN VERA', 'Femenino', 'gerenciahabitat@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIUXI PILAR', 'SALVATIERRA VERA', 'Femenino', 'mariusalvati@hotmail.com', '', '', '', '', 'Representante'),
		    array('RUTH KATIUSKA', 'JUNCO VANONI', 'Femenino', 'kattylee77@gmail.com', '0968077722', '', '', '', 'Representante'),
		    array('VICTOR JACINTO', 'QUINTERO CEVALLOS', 'Femenino', 'drvictorquintero@yahoo.es', '', '', '', '', 'Representante'),
		    array('MINY KARINA', 'AVILES HUACON', 'Femenino', 'karinavilh@gmail.com', '', '', '', '', 'Representante'),
		    array('YURI GASPAR', 'BARCO PACHECO', 'Femenino', 'yuribarcop@gmail.com', '', '', '', '', 'Representante'),
		    array('PAOLA URBANA', 'LLAGUNO VERA', 'Femenino', 'paolaconapu@hotmail.com', '', '', '', '', 'Representante'),
		    array('KARINA ROSCIBEL', 'MIELES CEVALLOS', 'Femenino', 'k-mieles@hotmail.com', '0994791541', '', 'villa españa 1 manzana 2277 villa 30', '2073550', 'Representante'),
		    array('LORENA ELIZABETH', 'SAAVEDRA RIOS', 'Femenino', 'lorena_saavedra_rios@hotmail.com', '0984439107', '', '', '', 'Representante'),
		    array('LISSETTE MARIELA', 'YEPEZ CEDEÑO', 'Femenino', 'lissmetal90@gmail.com', '', '', '', '', 'Representante'),
		    array('LAURA BENJAMINA', 'CARRERA GONZALEZ', 'Femenino', 'sincorreo12@gmail.com', '', '', '', '', 'Representante'),
		    array('CARLOS LUIS', 'CALDERON GUERRERO', 'Masculino', 'charliebrown_ec@yahoo.com', '0984147213', '', '', '', 'Representante'),
		    array('MARIA ELENA', 'MENA CASTRO', 'Femenino', 'maxyelen_73@hotmail.com', '', '', '', '', 'Representante'),
		    array('BETTY LEONOR', 'ESPIN MORAN', 'Femenino', 'nenaespin_1074@hotmail.com', '', '', '', '', 'Representante'),
		    array('VICTOR HUGO', 'ROMERO GUZMAN', 'Femenino', 'vromero.gpg@gmail.com', '', '', '', '', 'Representante'),
		    array('SONIA DE LOS ANGELES', 'QUINCHE AGUILAR', 'Femenino', 'sonia77_52@hotmail.com', '', '', '', '', 'Representante'),
		    array('JOHANNA SHAYLOT', 'ORTONEDA FAJARDO', 'Femenino', 'johanna.ortoneda@sqm.com', '0998082090', '', 'Metropolis 2B mz 1012 villa 25', '6045897', 'Representante'),
		    array('MARIELA ARMENIA', 'MARTINEZ PAREDES', 'Femenino', 'armeniafi@hotmail.com', '0985894522', '', '', '', 'Representante'),
		    array('IVONNE ROSALIA', 'SELLAN  MACIAS', 'Femenino', 'ivonnesellan@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('WILSON ASTOLFO', 'BOHORQUEZ CRUZ', 'Femenino', 'wilwilson_74@hotmail.com', '', '', '', '', 'Representante'),
		    array('YESENIA LEONOR', 'HOLGUIN LIGUA', 'Femenino', 'yesyjz11@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA LUISA', 'CALLE CARRERA', 'Femenino', 'mlcc75@hotmail.com', '0989851862', '', 'Alborada Etapa 12 mz 16 villa 8', '2273749', 'Representante'),
		    array('ALICIA JANETH', 'NUÑEZ PONCE', 'Femenino', 'alicianunez@interfilk.com', '0994542870', '', '', '', 'Representante'),
		    array('TANIA MARIANA', 'PINOARGOTE CORREA', 'Femenino', 'taniapc2006@hotmail.com', '0991753667', '', '', '', 'Representante'),
		    array('JESSICA DEL CARMEN', 'IBARRA MORALES', 'Femenino', 'ibarrajessica@hotmail.com', '', '', '', '', 'Representante'),
		    array('JUANA AURORA', 'TAYLOR MIELES', 'Femenino', 'juanitaylor@hotmail.com', '', '', '', '', 'Representante'),
		    array('ERICKA GUISELLE', 'VERA CARRION', 'Femenino', 'ericka.veracarrion@hotmail.com', '', '', 'urb La Rioja', '', 'Representante'),
		    array('KRISTHEL ILEANA', 'CHUCHUCA PALMA', 'Femenino', 'kriuschu06@hotmail.com', '', '', '', '', 'Representante'),
		    array('MIRYAM MARLENE', 'HUIRACOCHA QUINTERO', 'Femenino', 'miryamhuiracocha@hotmail.com', '2073125', '', 'Villafuerte España Madrid mz 223 v24', '2073125', 'Representante'),
		    array('RAQUEL DELIA', 'CHASI VILLEGAS', 'Femenino', 'k.eka75@hotmail.com', '', '', '', '', 'Representante'),
		    array('MONICA JANINA', 'BARRAZUETA QUEVEDO', 'Femenino', 'm_barrazueta_q@hotmail.com', '0969584648', '', '', '', 'Representante'),
		    array('FRANCISCO', 'MOSQUERA MORA', 'Femenino', 'franciscomosquera6@hotmail.com', '', '', '', '', 'Representante'),
		    array('ADRIANA ELIZABETH', 'CARDENAS SANCHEZ', 'Femenino', 'tanychris@hotmail.com', '', '', '', '', 'Representante'),
		    array('JAZMIN ELIZABETH', 'REGALADO ESPINOZA', 'Femenino', 'jregalad@yahoo.com', '', '', '', '', 'Representante'),
		    array('PATRICIA XIOMARA', 'PALIZ BENAVIDES', 'Femenino', 'xiomy.paliz@hotmail.com', '', '', '', '', 'Representante'),
		    array('ALDRIN', 'ZAMORA NARANJO', 'Femenino', 'azn2004@hotmail.com', '0996422581', '', '', '', 'Representante'),
		    array('NORMA PATRICIA', 'ZAMORA LITARDO', 'Femenino', 'norma@sqz.com.ec', '', '', '', '', 'Representante'),
		    array('KATTY YESENIA', 'IÑIGUEZ VALENCIA', 'Femenino', 'kainva@hotmail.com', '0998199317', '', 'Brisas del Rio', '2132939', 'Representante'),
		    array('DANNY ISAAC', 'VALLEJO CACHOTE', 'Femenino', 'dicvallejo@hotmail.com', '', '', '', '', 'Representante'),
		    array('LYDIA KARINA', 'MARIN MURILLO', 'Femenino', 'jvasquezdd@gmail.com', '0999999999', '', '', '', 'Representante'),
		    array('ALEXANDRA CRISTINA', 'SALAZAR MARTINEZ', 'Femenino', 'asalazar@agripac.com.ec', '0999426155', '', '', '', 'Representante'),
		    array('CARLOS OSWALDO', 'SANTILLAN SAMANIEGO', 'Femenino', 'sincorreo16@gmail.com', '', '', '', '', 'Representante'),
		    array('ROLANDO WASHINGTON', 'ORDOÑEZ PRADO', 'Femenino', 'rordonez_bayno@hotmail.com', '', '', '', '', 'Representante'),
		    array('SOLEDAD CRISTINA', 'OCEJO VARG', 'Femenino', 'comercialocejo@gmail.com', '', '', '', '', 'Representante'),
		    array('LEEVAN CLEEF', 'OJEDA DOMINGUEZ', 'Femenino', 'leecleef@yahoo.com', '', '', '', '', 'Representante'),
		    array('MIRYAN DEL PILAR', 'MORAN FIGUEROA', 'Femenino', 'miryam.moran@hotmail.com', '0959103183', '', '', '', 'Representante'),
		    array('MERCEDES ALEXANDRA', 'CARVAJAL ORRALA', 'Femenino', 'mcarvajalorrala@hotmail.com', '', '', '', '', 'Representante'),
		    array('PAMELA ALEXANDRA', 'ALEJANDRO TAPIA', 'Femenino', 'pamela_alejandro_tapia@hotmail.com', '', '', '', '', 'Representante'),
		    array('PATRICIA BEATRIZ', 'MARISCAL TOMALA', 'Femenino', 'pmariscaltomala@hotmail.com', '', '', '', '', 'Representante'),
		    array('OMAR AURELIANO', 'ZAPATA MURILLO', 'Femenino', 'ozapata@panatelcomm.com', '', '', '', '', 'Representante'),
		    array('LIRIA GEORGINA', 'LUNA GUTIERREZ', 'Femenino', 'bluemoonjadl@hotmail.com', '0991501757', '', 'Guayacanes mz 101 A v 10', '2820927', 'Representante'),
		    array('MARIA FERNANDA', 'IBAÑEZ APOLO', 'Femenino', 'maferita9@yahoo.com', '0985800390', '', 'Guayacanes Mz. 203 Villa 10', '046049293', 'Representante'),
		    array('ESPERANZA', 'COBEÑA SONIA', 'Femenino', 'spa.sonia@hotmail.com', '', '', '', '', 'Representante'),
		    array('JAHAIRA ELIZABETH', 'ROSADO TROYA', 'Femenino', 'sincorreo19@gmail.com', '', '', '', '', 'Representante'),
		    array('REINA', 'ORDOÑEZ DE URREA', 'Femenino', 'reinaordonezmoyano@hotmail.com', '0988642044', '', 'Urbanización Villa Club Etapa Doral mz. 4 villa  4', '2164800', 'Representante'),
		    array('CIRA SARITA', 'QUINTO CORTEZ', 'Femenino', 'saraquinto16@gmail.com', '', '', '', '', 'Representante'),
		    array('MIRIAM YOLANDA', 'MESIAS MONTERO', 'Femenino', 'sincorreo21@gmail.com', '', '', '', '', 'Representante'),
		    array('SILVIA ANA', 'RODRIGUEZ LOPEZ', 'Femenino', 'jimmy.xaviermd@hotmail.com', '', '', '', '', 'Representante'),
		    array('JESENNIA ALEXANDRA', 'VILLAMARIN GRANIZO', 'Femenino', 'jealvigr@gmail.com', '0980909011', '', '', '', 'Representante'),
		    array('INES MARIA', 'GUAMAN PAUCAR', 'Femenino', 'albertomasacela19@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('JORGE ENRIQUE', 'CHIRIBOGA ESPINOZA', 'Femenino', 'quinterok@hotmail.com', '0994909754', '', '', '5026057', 'Representante'),
		    array('CARLOS MANUEL', 'VARELA PATIÑO', 'Femenino', 'cvarel97@hotmail.com', '', '', '', '', 'Representante'),
		    array('NELLY ELIZABETH', 'PAREDES CARPIO', 'Femenino', 'nelly.paredes@outlook.com', '0999197807', '', '', '0987042618', 'Representante'),
		    array('JOSE VICENTE', 'PALMA CEVALLOS', 'Femenino', 'vicenpalm@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('MARTHA BEATRIZ', 'ESTRELLA SEGOVIA', 'Femenino', 'martha_estrella_77@hotmail.com', '', '', '', '', 'Representante'),
		    array('GABRIELA XAVIER', 'VILLAMAR NOVILLO', 'Femenino', 'gaby_4828@hotmail.com', '0992430797', '', '', '', 'Representante'),
		    array('MARIA LUISA', 'SOJOS ALVARADO', 'Femenino', 'marialuisasojos@hotmail.com', '', '', '', '', 'Representante'),
		    array('YOJANNA OLAVIDA', 'GILER MUÑOZ', 'Femenino', 'yo-j-ita@hotmail.com', '', '', '', '', 'Representante'),
		    array('CRISTIAN GILBERTO', 'MENDEZ MEDRANO', 'Masculino', 'cgmm1975@yahoo.es', '0959172418', '', 'Urbanización La Joya etapa Esmeralda MZ 13 villa 14', '046016292', 'Representante'),
		    array('MERCEDES ISABEL', 'SUAREZ GOYES', 'Femenino', 'mercedes_suarez77@hotmail.com', '', '', '', '', 'Representante'),
		    array('INGRID PATRICIA', 'ROMO-LEROUX GUTIERREZ', 'Femenino', 'iprlg-2@hotmail.com', '0988743626', '', 'Urbanización Matices, etapa Verde Esmeralda mz. 52 villa 4', '6035557', 'Representante'),
		    array('JORGE CARLOS', 'MURILLO ZAMBRANO', 'Femenino', 'george_m33@hotmail.com', '', '', '', '', 'Representante'),
		    array('TANIA ELIZABETH', 'BELTRAN MORAN', 'Femenino', 'sincorreo24@gmail.com', '', '', '', '', 'Representante'),
		    array('VERONICA', 'GALARZA PLAZA', 'Femenino', 'veronicagalarza77@hotmail.com', '0986184560', '', 'Urb Metropolis 02', '046016201', 'Representante'),
		    array('CARLOS SANUEL', 'PESANTEZ SIGUENZA', 'Femenino', 'spesantez_siguenza@hotmail.com', '0983461381', '', 'CDLA GUAYACANES MZ 7 VILLA 16', '042621767', 'Representante'),
		    array('MARIA ANGELICA', 'HERRERA MANTILLA', 'Femenino', 'maria.angelica.herrera.mantilla@gmail.com', '0962896417', '', '', '', 'Representante'),
		    array('ISABEL SUYEEN', 'WONG FUERTES', 'Femenino', 'suyeen0708@hotmail.com', '0992281300', '', 'URB LA JOYA ETAPA TURQUESA MZ 13 VILLA 12', '6002229', 'Representante'),
		    array('VERONICA DEL ROCIO', 'FIGUEROA GUZHÑAY', 'Femenino', 'verofique1@hotmail.com', '', '', '', '', 'Representante'),
		    array('JULIO PATRICIO', 'SANCHEZ ROSERO', 'Femenino', 'julio_sanchez1977@hotmail.com', '0986667949', '', 'brisas del norte', '5024041', 'Representante'),
		    array('JORGE  LUIS', 'SALAZAR  ZAMORA', 'Femenino', 'ing.jlsalazar@hotmail.com', '0982888659', '', 'Cdla. Guayacanes Mz 192 V 6', '042621232', 'Representante'),
		    array('GINA DEL ROCIO', 'MARTINEZ BANCHEN', 'Femenino', 'gina197580@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA DEL CARMEN', 'MATEO BRIONES', 'Femenino', 'mariacamateo@hotmail.com', '0988796198', '', '', '2231459', 'Representante'),
		    array('ERIKA MARIUXI', 'GARCIA GONZALES', 'Femenino', 'jerricka22@hotmail.com', '', '', 'CDLA. LA JOYA ETAPA CORONA MZ. 14 VILLA 12', '2624075', 'Representante'),
		    array('SUSAN ALEXANDRA', 'VERA MONTOYA', 'Femenino', 'sonjujonsu@hotmail.com', '', '', '', '', 'Representante'),
		    array('LENIN RAFAEL', 'ROJAS RUMBEA', 'Femenino', 'lenin-rojas@hotmail.com', '0960835002', '', '', '', 'Representante'),
		    array('ADRIANA LETICIA', 'PINTO ANDRADE', 'Femenino', 'adripinan@hotmail.com', '0982584116', '', 'sauces 2 mz 104 villa 1', '2236065', 'Representante'),
		    array('SOPHIA LORENA', 'LIMONES TOALA', 'Femenino', 'sophia.limones@gmail.com', '', '', 'Málaga 2 mz 8 v 11', '', 'Representante'),
		    array('VERONICA ELISA', 'BRIONES IZURIETA', 'Femenino', 'lisa_vero@hotmail.es', '0987162267', '', '', '', 'Representante'),
		    array('SANDRA HAYDEE', 'BARBOTO CASTRO', 'Femenino', 'sbarboto@hotmail.com', '', '', '', '', 'Representante'),
		    array('ERIK JAVIER', 'GUERRERO VERA', 'Femenino', 'erick_guerrero@hotmail.com', '', '', '', '', 'Representante'),
		    array('TATIANA ELIZABETH', 'GONZALEZ ORTIZ', 'Femenino', 'tegoortiz03@gmail.com', '0988258334', '', '', '', 'Representante'),
		    array('NANCY ELENA', 'ARAGUNDI PESANTEZ', 'Femenino', 'neap76@hotmail.com', '0988850996', '', 'Santiago City El Astillero Mz 2082 Villa 11', '4621873', 'Representante'),
		    array('MARIA FERNANDA', 'GONZALEZ GARCIA', 'Femenino', 'mafer_gonzalez@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARTHA ISABEL', 'HERAS JARA', 'Femenino', 'martha_hera_jara@hotmail.com', '', '', '', '', 'Representante'),
		    array('IRIS ISABEL', 'ARREAGA FUENTES', 'Femenino', 'iris_arreaga@outlook.com', '0999999999', '', '', '', 'Representante'),
		    array('MARIELISA DEL ROCIO', 'YANEZ SERRANO', 'Femenino', 'm.yanez24@hotmail.com', '0980780372', '', '', '', 'Representante'),
		    array('ROCIO', 'JACOME FERNANDEZ', 'Femenino', 'rfjf16@hotmail.com', '0990335460', '', '', '', 'Representante'),
		    array('HELEN YADIRA', 'HUACON SOJOS', 'Femenino', 'hhuacon2015@gmail.com', '0996426351', '', '', '', 'Representante'),
		    array('SILVIA EUGENIA', 'HOLGUIN AGUAS', 'Femenino', 'silvialuna16@hotmail.com', '0991628889', '', 'GUAYACANES', '2624825', 'Representante'),
		    array('JOSE MARTIN', 'JARA QUIJANO', 'Femenino', 'jjara2857@hotmail.com', '0985022133', '', '', '', 'Representante'),
		    array('INGRID JUANA', 'SOLA SEGURA', 'Femenino', 'isola29_seguro@hotmail.es', '', '', '', '', 'Representante'),
		    array('JAVIER EDUARDO', 'MALDONADO PEREZ', 'Femenino', 'javimp2@hotmail.com', '', '', '', '', 'Representante'),
		    array('JACQUELINE KENYA', 'COBA  GURUMENDI', 'Femenino', 'jacquicg401@hotmail.com', '0959071168', '', 'sauces 1 Mz F 9 villa 4', '2270000', 'Representante'),
		    array('LUIS JONATHAN', 'DORADO ORDOÑEZ', 'Femenino', 'cpa/dorado@gmail.com', '', '', '', '', 'Representante'),
		    array('LUZ C', 'NEIRA GARCIA', 'Femenino', 'isabeldalia@hotmail.com', '', '', 'Sauces 3 mz 140', '2-572-938', 'Representante'),
		    array('MARIA VERONICA', 'LUDEÑA MACIAS', 'Femenino', 'veroludena@hotmail.com', '', '', '', '', 'Representante'),
		    array('ROSA VICTORIA', 'SUAREZ CEVALLOS', 'Femenino', 'locutoriolacuesta@hotmail.com', '', '', '', '', 'Representante'),
		    array('ROCIO DEL CARMEN', 'CEDEÑO BARCIA', 'Femenino', 'chiocedeno@gmail.com', '0985941285', '', 'Duran', '042196431', 'Representante'),
		    array('LOURDES', 'CADENA TACLE', 'Femenino', '2lcadena@gmail.com', '0999999999', '', '', '', 'Representante'),
		    array('SAUL XAVIER', 'CAAMAÑO ARIAS', 'Femenino', 'perroso2001@hotmail.com', '', '', '', '', 'Representante'),
		    array('EDISON EFREN', 'CABRERA CERCADO', 'Femenino', 'cabrera_edison@yahoo.com', '0996127939', '', 'Ciudad del Rio I mz 971 v 10', '2157566', 'Representante'),
		    array('DIANA CATHERINE', 'ARROBA SANTOS', 'Femenino', 'diana_arroba@hotmail.com', '', '', '', '', 'Representante'),
		    array('MONICA ALEXANDRA', 'PARREÑO  QUIÑONEZ', 'Femenino', 'monicaalexandra1980parreno@gmail.com', '0999999999', '', '', '', 'Representante'),
		    array('IRMA LORENA', 'SOTOMAYOR MARTINEZ', 'Femenino', 'gracie_so79@hotmal.com', '899999999', '', '', '', 'Representante'),
		    array('LUIS DANIEL', 'PASTOR LADINEZ', 'Femenino', 'danpastor2604@hotmail.com', '0989234123', '', 'Urb. La Joya etapa Esmeralda Mz5 v25', '2070999', 'Representante'),
		    array('VICENTE ARMANDO', 'RUIZ ESPINOZA', 'Femenino', 'vicore@hotmail.com', '0996030568', '', 'Ciudad del Rio Mz.971 V.9', '042157512', 'Representante'),
		    array('RUTH ANGGIE', 'TORRES TORRES', 'Femenino', 'ruthanggie94@hotmail.com', '', '', '', '', 'Representante'),
		    array('RODOLFO ISRAEL', 'CHIRIBOGA CRUZ', 'Masculino', 'rodolfochiriboga@hotmail.com', '0983319241', '', '', '', 'Representante'),
		    array('CAROLINA JANINA', 'CORTEZ MERA', 'Femenino', 'caro_cortez_m@hotmail.com', '', '', '', '', 'Representante'),
		    array('JORGE WHASINGTON', 'MATEO VELEZ', 'Femenino', 'jmateov@hotmail.com', '', '', '', '', 'Representante'),
		    array('GISELLA', 'CAMPOVERDE OCHOA', 'Femenino', 'gigicampochoa@gmail.com', '', '', '', '', 'Representante'),
		    array('SAYONARA NORMA', 'LACA GUALE', 'Femenino', 'sayo.lg@hotmail.com', '', '', '', '', 'Representante'),
		    array('ELIANA LISSETH', 'DONOSO CASTRO', 'Femenino', 'lisseth.donosoc@gmail.com', '', '', '', '', 'Representante'),
		    array('MESIAS FLORENCIO', 'CULCAY ZAMBRANO', 'Femenino', 'mesiasculcay@yahoo.com', '', '', '', '', 'Representante'),
		    array('RICARDO DAVID', 'MOSQUERA JIMENEZ', 'Femenino', 'sincorreo29@gmail.com', '', '', '', '', 'Representante'),
		    array('JORGE LUIS', 'GARCIA LUZARDO', 'Femenino', 'jlgarcia@telconet.ec', '', '', '', '', 'Representante'),
		    array('SANDRA ELIZABETH', 'GUAMAN DIAZ', 'Femenino', 'elizaminino@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARTHA FERNANDA', 'OTAVALO RESABALA', 'Femenino', 'martyta@hotmail.com', '', '', '', '', 'Representante'),
		    array('ELSA JUDITH', 'DONOSO MOLINA', 'Femenino', 'elsadonoso83@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA FERNANDA', 'GUTIERREZ ZAMBRANO', 'Femenino', 'mgutierrez@tctelevision.com', '0981149985', '', '', '', 'Representante'),
		    array('CARLOS EDUARDO', 'ROMO PONCE', 'Masculino', 'jennycvillafuertes@gmail.com', '9999999999', '', '', '', 'Representante'),
		    array('MAIRA GEOCONDA', 'SUAREZ VELIZ', 'Femenino', 'mayrasuarezv@hotmail.com', '0995233470', '', 'Metrópolis 2H Mz 1283 V 12', '046027054', 'Representante'),
		    array('KARINA', 'VERDUGO PEREZ', 'Femenino', 'david_gamar@hotmail.com', '0984805643', '', '', '', 'Representante'),
		    array('DENNYS MIGUEL', 'MARQUEZ FALQUEZ', 'Masculino', 'blanca_vale1@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('IVAN LEONEL', 'BELTRAN SOLORZANO', 'Femenino', 'ivbel@hotmail.com', '', '', '', '', 'Representante'),
		    array('OLGA MARIA', 'PERDOMO BRIONES', 'Femenino', 'olguisperdof@gmail.com', '0969290928', '', '', '', 'Representante'),
		    array('LILIANA EVELYN', 'FIGUEROA CARPIO', 'Femenino', 'liliana_fc05@hotmail.com', '0997991536', '', '', '', 'Representante'),
		    array('EVELYN NEREYDA', 'PAEZ CALI', 'Femenino', 'epaez@granotec.com.ec', '', '', '', '', 'Representante'),
		    array('GLENDA MARTHA', 'QUIROZ MORAN', 'Femenino', 'glendy_quiroz@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('NORMAN RODOLFO', 'MUÑOZ VILLALTA', 'Femenino', 'chinonorman@hotmail.com', '0994487646', '', 'SAN TORINI BLOQUE 8 V54', '046012900', 'Representante'),
		    array('EVELYN JAZMIN', 'HINOJOSA GUEVARA', 'Femenino', 'alexms_v@hotmail.com', '', '', '', '', 'Representante'),
		    array('JOSE CARLOS', 'GONZALEZ QUEVEDO', 'Femenino', 'sincorreo34@gmail.com', '', '', '', '', 'Representante'),
		    array('JOSE LUIS', 'CUEVA LEON', 'Masculino', 'jcueec@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('MAYITA JISSELA', 'MACIAS ALAVA', 'Femenino', 'aywlian@hotmail.com', '', '', '', '', 'Representante'),
		    array('NARIA ELENA', 'OLAYA PINCAY', 'Femenino', 'marielena_olaya@hotmail.com', '', '', '', '', 'Representante'),
		    array('FLOR MARIA', 'MARIÑO LUA', 'Femenino', 'sugey_mlua1982@hotmail.com', '', '', '', '', 'Representante'),
		    array('SULLY SULLIN', 'SALTOS  GAVILANES', 'Femenino', 'sullysaltos17@hotmail.com', '', '', '', '', 'Representante'),
		    array('SILVIA VANESSA', 'ALAVA SANCHEZ', 'Femenino', 'vane.alava@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIAN VERONICA', 'SALAZAR CALDERON', 'Femenino', 'veritosalazar1212@gmail.com', '', '', '', '', 'Representante'),
		    array('LISBETT EDITH', 'MORALES FABARA', 'Femenino', 'lisbettmorales@outlook.es', '0994973221', '', '', '', 'Representante'),
		    array('WENDY NATALIA', 'VALLEJO CACHOTE', 'Femenino', 'wendy.vallejo@hotmail.com', '', '', '', '', 'Representante'),
		    array('ALBA MARITZA', 'MIELES VINCES', 'Femenino', 'marymieles77@hotmail.com', '', '', '', '', 'Representante'),
		    array('EDDY SANTIAGO', 'MIELES MACIAS', 'Femenino', 'smielesmacias@hotmail.com', '0997261656', '', 'METROPOLIS IIC MZ.918 VILLA 14', '2827049', 'Representante'),
		    array('ERIKA KATIUSKA', 'VIDAL CORDOVA', 'Femenino', 'katuvid11@hotmail.com', '0984714535', '', '', '', 'Representante'),
		    array('YICELA MARIA', 'MUÑOS CANDELA', 'Femenino', 'YICELAMUNOSCANDELA@HOTMAIL.COM', '', '', '', '', 'Representante'),
		    array('OSCAR OSWALDO', 'ROCA TENEMASA', 'Femenino', 'oskar_rok@hotmail.com', '', '', '', '', 'Representante'),
		    array('LIZCET ALEXANDRA', 'FLORES SALAZAR', 'Femenino', 'lizcet_fs@hotmail.com', '', '', '', '', 'Representante'),
		    array('JOHANNA LUISA', 'ESPINOZA MENDIZABAL', 'Femenino', 'jems.espinoza@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA DE LOS ANGELES', 'JIMENEZ RODRIGUEZ', 'Femenino', 'mariajimenezrod@hotmail.com', '', '', '', '', 'Representante'),
		    array('LEOPOLDO ERNESTO', 'VALLEJO COBEÑA', 'Femenino', 'sincorreo36@gmail.com', '', '', '', '', 'Representante'),
		    array('ANA DEL PILAR', 'MENA FLORES', 'Femenino', 'luisarevalo20062006@hotmail.com', '', '', '', '', 'Representante'),
		    array('FLORES ZAPATA', 'ROXANA DEL PILAR', 'Femenino', 'r.flores.z@hotmail.com', '0995734734', '', '', '', 'Representante'),
		    array('MERCY ALEXANDRA', 'GUILLEN MORA', 'Femenino', 'magon10@hotmail.com', '', '', '', '', 'Representante'),
		    array('RAQUEL RITA', 'GONZALEZ PALADINES', 'Femenino', 'raquelyada@hotmail.com', '0958766010', '', '', '', 'Representante'),
		    array('PATRICIA ROCIO', 'NAULA QUIZPHI', 'Femenino', 'pnaula@hotmail.com', '0969087568', '', 'Villa España 1 etapa Sevilla mz.2112 Villa 13', '2298504', 'Representante'),
		    array('SHIRLEY ERIKA', 'ZAMBRANO VASQUEZ', 'Femenino', 'sezambranov@hotmail.com', '0995493300', '', 'La joya', '042732192', 'Representante'),
		    array('JENNY MARIELA', 'RONQUILLO CARPIO', 'Femenino', 'jemarielaronquillo@gmail.com', '0999469639', '', '', '', 'Representante'),
		    array('MARY', 'MERCHAN NAVARRETE', 'Femenino', 'mary.mnconcep@gmail.com', '0991545855', '', 'guayacanes mz37 v#9', '', 'Representante'),
		    array('MARIA INES', 'ARIZAGA SANTANA', 'Femenino', 'manine071981@gmail.com', '0992852538', '', 'Guayacanes mz 161 v, 16', '', 'Representante'),
		    array('WENDY PAOLA', 'BARRERA LUCES', 'Femenino', 'wentpao23@hotmail.com', '0987603659', '', 'Alborada 1era etapa MZ. C', '', 'Representante'),
		    array('DIANA PILAR', 'CEVALLOS RODRIGUEZ', 'Femenino', 'dianitacr9@hotnail.com', '', '', '', '', 'Representante'),
		    array('YSAURA LEONOR', 'BUSTE CARPIO', 'Femenino', 'isaura66@hotmail.com', '', '', 'Sauces 4', '', 'Representante'),
		    array('EUGENIA JANETH', 'PAZMIÑO LA ROSA', 'Femenino', 'janethlarosa@hotmail.com', '', '', '', '', 'Representante'),
		    array('MATILDE DANIELA', 'FRANCO ALVARADO', 'Femenino', 'dfranco@fiducia.com.ec', '', '', '', '', 'Representante'),
		    array('JOHANA JAMINA', 'MACIAS GARCIA', 'Femenino', 'johana198189@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('Ericka', 'Loor López', 'Femenino', 'erickahloorl_0506@hotmail.com', '0987697579', '', 'Geranios 2', '', 'Representante'),
		    array('ADRIANA MAGDALENA', 'MENDOZA PALACIOS', 'Femenino', 'adrianamendoza@incarpalm.com.ec', '0989629004', '', '', '', 'Representante'),
		    array('MIRIAN ELIZABETH', 'ANDINO ULLAURI', 'Femenino', 'mandino1981@hotmail.com', '0984115127', '', 'Alborada 11va etapa manzana 27 villa 18', '2176379', 'Representante'),
		    array('SHIRLEY CAROLINA', 'CRUZ FRANCO', 'Femenino', 'shirley.cruz@grupodifare.com', '', '', '', '', 'Representante'),
		    array('WENDY VANESSA', 'BRAVO TAPIA', 'Femenino', 'wendybravotapia@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARTHA ILSE', 'VALLE GOMEZ', 'Femenino', 'ilse_valle_gomez@hotmail.com', '', '', '', '', 'Representante'),
		    array('PRISCILA ANGELICA', 'JARAMILLO VILLAMAR', 'Femenino', 'sincorreo37@gmail.com', '', '', '', '', 'Representante'),
		    array('SILVIA ALEXANDRA', 'CORTES ROMOLEROUX', 'Femenino', 'scortesromoleroux@gmail.com', '0969312426', '', '', '', 'Representante'),
		    array('DENNIS ELIZABETH', 'BETANCOURT MAGALLANES', 'Femenino', 'sincorreo38@gmail.com', '', '', '', '', 'Representante'),
		    array('ELSI MARIELISA', 'BURGOS SILVA', 'Femenino', 'sincorreo39@gmail.com', '', '', '', '', 'Representante'),
		    array('JENNY VERONICA', 'BOHORQUEZ ONOFRE', 'Femenino', 'jv.gordita@hotmail.com', '', '', '', '', 'Representante'),
		    array('CARLOS', 'VALDIVIEZO FLORES', 'Femenino', 'fabricio_klt@hotmail.com', '0991376798', '', 'Guayaycanes mz 232 v 26', '042822481-0991376798', 'Representante'),
		    array('LENIN MEDARDO', 'MONAR CARRILLO', 'Femenino', 'lmonarc@hotmail.com', '0997402577', '', 'Samanes 2 Mz. 202 V. 12', '042215437', 'Representante'),
		    array('ROSSINA DEL PILAR', 'VITE ZAVALA', 'Femenino', 'rossinavite82@hotmail.com', '', '', '', '', 'Representante'),
		    array('CINTHYA LORENA', 'PAREDES MACIAS', 'Femenino', 'cinttya.paredes83@gmail.com', '', '', '', '', 'Representante'),
		    array('MARIANELLA PAULINA', 'ROBLES CHAFLA', 'Femenino', 'paulina_marianella@hotmail.com', '', '', '', '', 'Representante'),
		    array('LADY SUSANA', 'MERCHAN AGUILAR', 'Femenino', 'lady1805@hotmail.com', '0982869899', '', '', '', 'Representante'),
		    array('INDIRA ERICKA', 'ANDRADE MIRANDA', 'Femenino', 'rlmiranda49@hotmail.com', '0980872871', '', '', '', 'Representante'),
		    array('KATHERINE ALEXANDRA', 'ROBLES CHAFLA', 'Femenino', 'kalexrobles@hotmail.com', '', '', '', '', 'Representante'),
		    array('CINTHYA LISSETH', 'MIRANDA MORAN', 'Femenino', 'm_miranda@hotmaIl.com', '', '', '', '', 'Representante'),
		    array('MARIA LORENA', 'HERRERA ALAVA', 'Femenino', 'sincorreo40@gmail.com', '', '', '', '', 'Representante'),
		    array('DENISSE ESTEFANÍA', 'RAMIREZ SUAREZ', 'Femenino', 'estefanie_ders18@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA GABRIELA', 'MERA ROMERO', 'Femenino', 'meragaby@hotmail.com', '', '', '', '', 'Representante'),
		    array('PAMELA ANDREA', 'VILLAO CALLE', 'Femenino', 'pamelaiamy@hotmail.es', '', '', '', '', 'Representante'),
		    array('FANNY ALEXANDRA', 'CARVAJAL GUTIERREZ', 'Femenino', 'fanylu_82@hotmail.es', '', '', '', '', 'Representante'),
		    array('MARIUXI JAZMIN', 'PANTA ARIAS', 'Femenino', 'argentina_arias1956@hotmail.com', '0985739914', '', 'Villa Club Mz 12 V. 14', '2984474', 'Representante'),
		    array('MARIA ELENA', 'SALINAS SALINAS', 'Femenino', 'mariasalinas1982@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('MERCEDES CECILIA', 'PARRA TAPIA', 'Femenino', 'mercedes_alejita@hotmail.com', '0988446534', '', '', '', 'Representante'),
		    array('MARIA SOLEDAD', 'REA FAJARDO', 'Femenino', 'soledadrea@gmail.com', '0983217835', '', '', '', 'Representante'),
		    array('LINA MARITZA', 'CHOEZ PINTO', 'Femenino', 'lina656@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA FERNANDA', 'BUCHELI  RODRIGUEZ', 'Femenino', 'mafer1785@hotmail.com', '0993230816', '', 'villa del rey -etapa felipe mz 4 villa 52', '046009971', 'Representante'),
		    array('ANGELICA MARIA', 'VALENCIA ANDRADE', 'Femenino', 'AMVA.83@HOTMAIL.COM', '', '', '', '', 'Representante'),
		    array('GINA MARIA', 'CEVALLOS ZAMBRANO', 'Femenino', 'ginacevallos1991@gmail.com', '0993874262', '', '', '', 'Representante'),
		    array('CRISTINA VALERIA', 'TORRES JAME', 'Femenino', 'alejandrohb1805@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('SHIRLEY JOHANNA', 'CHIRIGUAYA PACHAY', 'Femenino', 'elmundodelosdeseos@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('NELLY ELIZABETH', 'MORAN JARA', 'Femenino', 'nellymoran18@gmail.com', '042623572', '', '', '', 'Representante'),
		    array('YAJAIRA JAZMIN', 'FLORES CASTRO', 'Femenino', 'yajaju2020@hotmail.com', '', '', '', '', 'Representante'),
		    array('RICARDO MIGUEL', 'IÑIGUEZ VALENCIA', 'Femenino', 'elect-arturo-iniguez@hotmail.com', '', '', '', '', 'Representante'),
		    array('LORENA JACQUELINE', 'VELEZ TUMBACO', 'Femenino', 'heidi-2320@hotmail.com', '', '', '', '', 'Representante'),
		    array('NIBARDO ANDRES', 'LOZANO ANDRADE', 'Masculino', 'andreslozano@outlook.com', '0993029505', '', '', '', 'Representante'),
		    array('ALICIA IVANOVA', 'ESPINOZA  ORTIZ', 'Femenino', 'alcia.espinoza.o@gmail.com', '', '', '', '', 'Representante'),
		    array('AURELINA DEL CARMEN', 'PARRAGA HOLGUIN', 'Femenino', 'linaparragaholguin@hotmail.com', '', '', '', '', 'Representante'),
		    array('IVETTE DE LOS ANGELES', 'RODRIGUEZ SANCHEZ', 'Femenino', 'ivetteangeles.rodriguez@gmail.com', '', '', '', '', 'Representante'),
		    array('MARIA ANGELICA', 'POZO VINTIMILLA', 'Femenino', 'angelicapozo1985@gmail.com', '0967700265', '', 'Sauces 6 Mz 344 villa 11', '0967700265 - 0959440705', 'Representante'),
		    array('VERONICA', 'MOLINA VILLACIS', 'Femenino', 'vemovi@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('LORENA', 'SEVILLA DUEÑAS', 'Femenino', 'lorenitasevilla239@gmail.com', '', '', '', '', 'Representante'),
		    array('GABRIELA VIVIANA', 'RUBIO LLAQUE', 'Femenino', 'gaby_200589@hotmail.com', '', '', '', '', 'Representante'),
		    array('NATHALY FRANCISCA', 'PARRA TAPIA', 'Femenino', 'nathalyparrat@gmail.com', '', '', '', '', 'Representante'),
		    array('ANDREA DENISSE', 'NUÑEZ GARCES', 'Femenino', 'andreanvo5@gmail.com', '', '', '', '', 'Representante'),
		    array('TATIANA CECIBEL', 'VILLAMAR BAQUERIZO', 'Femenino', 'tati.villamar@hotmail.com', '', '', '', '', 'Representante'),
		    array('LADY ZULEMA', 'MANZUR ROJAS', 'Femenino', 'lady_manzur@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA FERNANDA', 'LINDAO MANTUANO', 'Femenino', 'm-a-ferl@hotmail.com', '', '', '', '', 'Representante'),
		    array('ELVIS IVAN', 'MORAN AVILES', 'Masculino', 'elvisema85@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('INES KATTY', 'GOYA SALDAÑA', 'Femenino', 'katty_goya01@hotmail.com', '0999516996', '', 'VILLA ESPAÑA', '', 'Representante'),
		    array('GALO EDMUNDO', 'LEMA TUPIZA', 'Femenino', 'galo450@hormail.com', '', '', '', '', 'Representante'),
		    array('NORMA ROSALIA', 'MARQUEZ ZAMBRANO', 'Femenino', 'sagato-22@hotmail.com', '0968254098', '', 'Guayacanes Mz 59 Sl 20', '5054829', 'Representante'),
		    array('ALEX', 'RIVERA ARCOS', 'Femenino', 'sincorreo42@gmail.com', '', '', '', '', 'Representante'),
		    array('AURA CRISTINA', 'MENDOZA MOLINA', 'Femenino', 'autiti22@hotmail.com', '', '', '', '', 'Representante'),
		    array('GISLEY CAROLINA', 'FRANCO MORAN', 'Femenino', 'gisley_franco18@hotmail.com', '0982285859', '', 'Guayacanes Mz. 98B V. 13', '042621237', 'Representante'),
		    array('XAVIER FEDERICO', 'ECHEVERRIA SANCHEZ', 'Femenino', 'xavier75e@yahoo.com', '', '', '', '', 'Representante'),
		    array('CARLOS ANDRES', 'MONTERO BERMUDEZ', 'Masculino', 'frobalino_caritafeliz@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('DIANA MARLENE', 'SOLORZANO GUTIERREZ', 'Femenino', 'dianasolorzanog@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('OSCAR DANIEL', 'ARAMBULO CEPEDA', 'Femenino', 'obscar23@gmail.com', '0993405624', '', 'CDLA LOS VERGELES MZ. 64C V. 39', '042019267', 'Representante'),
		    array('VALERIA GYANELLA', 'PARRA  TERAN', 'Femenino', 'valegparra@outlook.com', '', '', '', '', 'Representante'),
		    array('TATIANA LUCILA', 'QUINTERO MUÑOZ', 'Femenino', 'taty_quinteros@hotmail.com', '0997215264', '', 'Jardines del rio mz 27 villa 33 autopista', '222666', 'Representante'),
		    array('GIANELLA ISABEL', 'QUIMIS BALON', 'Femenino', 'gianellaamor@hotmail.com', '0980170998', '', '', '', 'Representante'),
		    array('MARIA GABRIELA', 'BUSTAMANTE REYES', 'Femenino', 'magabust@espol.edu.ec', '0992798362', '', 'URBANIZACION JARDINES DEL RIO MZ 29 VILLA 43', '042167551', 'Representante'),
		    array('LADY DALILA', 'FERNANDEZ GALVEZ', 'Femenino', 'ladyc_1623@hotmail.com', '0961357555', '', 'Floresta 3 Mz D V1', '2495347', 'Representante'),
		    array('MARIA ANDREA', 'CORTEZ FAJARDO', 'Femenino', 'andreacortez_20_03@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARISOL ANDREA', 'ORTEGA GOMEZ', 'Femenino', 'mortegasa@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('NORMA ALEXANDRA', 'ALAVA SARMIENTO', 'Femenino', 'normalex-10@hotmail.com', '', '', '', '', 'Representante'),
		    array('ANA VICENTA', 'VERA LOPEZ', 'Femenino', 'anaveralope@hotmail.com', '0967973800', '', 'Sauces 4 bloques de la armada #4 dep 102', '', 'Representante'),
		    array('VICENTE JAVIER', 'VERA PEREZ', 'Femenino', 'vicente_vera_p@hotmail.com', '0969370503', '', 'Guayacanes 1era Etapa mz. 66 villa 10', '042 - 823108', 'Representante'),
		    array('GABRIELA STEFANIA', 'GOMEZ CAMPODONICO', 'Femenino', 'gabyg_x@hotmail.com', '0991096299', '', 'Urb. La Joya, etapa Perla Mz. 1 V. 7', '2827048', 'Representante'),
		    array('ANDREA ESTEFANIA', 'DELGADO PINARGOTE', 'Femenino', 'sincorreo43@gmail.com', '', '', '', '', 'Representante'),
		    array('ERIKA PAULINA', 'TACURI NIVELA', 'Femenino', 'erikatacuri16@hotmail.com', '0959292270', '', 'Sauces 4 Mz. 362 V. 25', '2623649', 'Representante'),
		    array('DIGNA NARCISA', 'LEON HARO', 'Femenino', 'longeva-sinopsis.23@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA EUGENIA', 'GALVEZ CAMPUZANO', 'Femenino', 'marygalcam@hotmail.com', '', '', '', '', 'Representante'),
		    array('LISSETTE AMELIA', 'ALVARADO AJILA', 'Femenino', 'lissgalva@hotmail.com', '', '', '', '', 'Representante'),
		    array('VICTORIA CAROLINA', 'ROJAS RIVERA', 'Femenino', 'sincorreo44@gmail.com', '', '', '', '', 'Representante'),
		    array('JORGE LUIS', 'GALLO ANTE', 'Femenino', 'sincorreo45@gmail.com', '', '', '', '', 'Representante'),
		    array('CYNTHIA GIANINA', 'MORAN DUMES', 'Femenino', 'cynthiecita_loveunico@hotmail.com', '', '', '', '', 'Representante'),
		    array('JANINA ANDREA', 'CHILUIZA PINCAY', 'Femenino', 'j.chiluiza@hotmail.com', '', '', '', '', 'Representante'),
		    array('TATIANA ESPERANZA', 'GALARZA ESPINOSA', 'Femenino', 'tatiana13_19@hotmail.com', '0939726199', '', 'Sauces 9 mz L13 V1', '045035790', 'Representante'),
		    array('PATRICIA DEYANIRA', 'ZERNA GAVILANES', 'Femenino', 'patriciadeyanira89@gmail.com', '0997174350', '', 'Urbanización La Romareda Etapa 1 Manzana 1984 villa 5', '4548942', 'Representante'),
		    array('KONNY MARIA', 'SEMPERTEGUI SAN LUCAS', 'Femenino', 'kmsempertegui@gmail.com', '', '', '', '', 'Representante'),
		    array('TAMARA ABIGAIL', 'QUIZHPE GUAPULEMA', 'Femenino', 'silviamm3@hotmail.com', '', '', '', '', 'Representante'),
		    array('ANA KAREN', 'ALAVA CARBO', 'Femenino', 'anydannae@gmail.com', '0998187441', '', 'Cooperativa Juan Pablo II Mz2355 sl10', '2131673', 'Representante'),
		    array('MARIA FERNANDA', 'REMACHE NIETO', 'Femenino', 'fernandoremache_transfer@hotmail.com', '', '', '', '', 'Representante'),
		    array('REBECA KAREN', 'FRANCO VASQUEZ', 'Femenino', 'rebekitaraph_23@hotmail.com', '', '', '', '', 'Representante'),
		    array('CARLOS VICENTE', 'TAPIA SOLORZANO', 'Femenino', 'carvitaso@gmail.com', '', '', '', '', 'Representante'),
		    array('ADRIANA PAOLA', 'SOTOMAYOR OCHOA', 'Femenino', 'apso_s@hotmail.com', '', '', '', '', 'Representante'),
		    array('CRISTINA CIELO', 'NUÑEZ DEL ARCO PALACIOS', 'Femenino', 'coroneljoseluis@hotmail.com', '', '', '', '', 'Representante'),
		    array('SILVANIA JENNIFFER', 'ORMEÑO TIGUA', 'Femenino', 'silvaniaormeno@hotmail.com', '', '', '', '', 'Representante'),
		    array('GENESIS YAMILA', 'CARRILLO TORRES', 'Femenino', 'gene_carrillo_13@hotmail.com', '0960130500', '', 'Urb estrella de mar mz 2 v 13', '2-029393', 'Representante'),
		    array('KATTY NAZIRA', 'MORENO HERRERA', 'Femenino', 'kattymoreno90@gmail.com', '', '', 'Guayacanes mz59', '042823102', 'Representante'),
		    array('KAREN JHOMAYRA', 'LLANEZ BELTRAN', 'Femenino', 'kllanezbeltran@gmail.com', '0989618869', '', 'cdla lotes con servicio la alegria mz 1553 sl 3y4', '042120939', 'Representante'),
		    array('ESTHELA DEL CARMEN', 'DIAZ DIAS', 'Femenino', 'caramelitozoe@hotmail.com', '0989465230', '', '', '', 'Representante'),
		    array('ALEXANDRA ELIZABETH', 'CAMPUZANO VERA', 'Femenino', 'alexandracampuzanovera@hotmail.com', '0967866235', '', '', '', 'Representante'),
		    array('GENOVA GUISELLA', 'ESCOBAR BAJAÑA', 'Femenino', 'genovaescobar1@gmail.com', '', '', '', '', 'Representante'),
		    array('FERMIN ANDRES', 'VERA CARRION', 'Femenino', 'fer7_andres@hotmail.com', '', '', '', '', 'Representante'),
		    array('GABRIEL EMMANUEL', 'VILLEGAS BARRERA', 'Masculino', 'deejaydaga@hotmail.com', '0960297968', '', '', '', 'Representante'),
		    array('JORGE ALBERTO', 'YEE GUIN', 'Femenino', 'jyg41@hotmail.com', '0993210143', '', 'Urb. La Rioja - Etapa Asturias Mz 5 villa 1', '0993210143', 'Representante'),
		    array('ANDREA PATRICIA', 'RUPERTTI FAJARDO', 'Femenino', 'andypertty247@gmail.com', '0985075061', '', '', '', 'Representante'),
		    array('SCARLETT BRIGGITTE', 'VERA ALVARADO', 'Femenino', 'ricardo_alfonso@hotmail.com', '', '', '', '', 'Representante'),
		    array('IVETTE CAROLINA', 'ANDRADE VACA', 'Femenino', 'ivette_carito_lin@hotmail.com', '0988659667', '', '', '', 'Representante'),
		    array('CESAR XAVIER', 'FAJARDO HERRERA', 'Femenino', 'xavi_fa_he@hotmail.com', '', '', '', '', 'Representante'),
		    array('JAVIER WILFRIDO', 'ANDRADE MENDOZA', 'Femenino', 'sincorreo51@gmail.com', '', '', '', '', 'Representante'),
		    array('CAROLINA MARIBEL', 'JARAMILLO BURGOS', 'Femenino', 'caritomari_91@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIELISA', 'RUEDA CONTRERAS', 'Femenino', 'marielisarueda@hotmail.com', '0994632931', '', 'Estrella de Mar Mz 9 V18', '04 2029602', 'Representante'),
		    array('DANNY GABRIEL', 'MACIAS SALAZAR', 'Femenino', 'arq.dannymacias@gmail.com', '', '', '', '', 'Representante'),
		    array('SHU', 'WANG', 'Femenino', 'w.s.sasan@hotmail.com', '', '', '', '', 'Representante'),
		    array('ROBERTO CARLOS', 'FRANCO  FIGUEROA', 'Femenino', 'robert4feb@hotmail.com', '', '', '', '', 'Representante'),
		    array('TATIANA ELIZABETH', 'ANDRADE PEREZ', 'Femenino', 'sincorreo52@gmail.com', '', '', '', '', 'Representante'),
		    array('MARTHA BEATRIZ', 'MOROCHO USHCA', 'Femenino', 'tuadonis20@hotmail.com', '0978843294', '', 'Guayacanes Mz 16 V1', '0978843294', 'Representante'),
		    array('VICTORIA ESCARLETH', 'DELGADO CEDEÑO', 'Femenino', 'victoriadc20@hotmail.com', '0967891593', '', 'Guayacanes Mz 107 Villa 12', '2828410', 'Representante'),
		    array('JENNIFER ROSARIO', 'CEDEÑO TRIANA', 'Femenino', 'cielobello.19@hotmail.com', '0959909370', '', '', '', 'Representante'),
		    array('GINGER ESTEFANIA', 'HEREDIA PINCAY', 'Femenino', 'gingerheredia25@hotmail.com', '0982881096', '', 'Los Vergeles Mz. 87 Villa 2', '042026638', 'Representante'),
		    array('VICTOR GUSTAVO', 'GOMEZ RODRIGUEZ', 'Femenino', 'vggomez2008@gmail.com', '0991924130', '', '', '', 'Representante'),
		    array('LILIBETH', 'DURAN MONCADA', 'Femenino', 'lilibeth.duran.m@gmail.com', '0981869707', '', 'Urbanizacion Estrella del Mar Maz 9 v7', '', 'Representante'),
		    array('PEDRO LUIS', 'POLO MARAZITA', 'Femenino', 'pedropolo19@hotmail.com', 'O991854889', '', 'CiudadCeleste', '6025178', 'Representante'),
		    array('LINDA JULIETA', 'COELLO GUERRERO', 'Femenino', 'justinsoledispa@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARINA NARCISA', 'VELEZ WONG', 'Femenino', 'marvelwo-intervex@hotmail.com', '0984747147', '', '', '', 'Representante'),
		    array('ROSARIO PIEDAD', 'SANTANA ZAMORA', 'Femenino', 'sharonsantana63@hotmail.com', '', '', '', '', 'Representante'),
		    array('NORMA ALEXANDRA', 'BANCHON VASQUEZ', 'Femenino', 'alex_banchon@yahoo.com', '0989519191', '', 'Cdla. Jardines del Rio', '', 'Representante'),
		    array('NIDIA GUISELA', 'BAJAÑA MOREIRA', 'Femenino', 'nidiabajanamoreira2017@gmail.com', '', '', '', '', 'Representante'),
		    array('JOSE FERNANDO', 'GAVILANES PONTE', 'Femenino', 'fersanjuan69@yahoo.mail', '', '', '', '', 'Representante'),
		    array('ABEL ROMEO', 'CARRERA GONZALEZ', 'Femenino', 'acarrera@ecua.net.ec', '', '', '', '', 'Representante'),
		    array('BLANCA MIREYA', 'VERA VERA', 'Femenino', 'loorvera_1974@hotmail.com', '0987224965', '', 'Acuarela del rio', '5020468', 'Representante'),
		    array('MARILYN MARTHA', 'LOOR BARROS', 'Femenino', 'mloorbarros2015@gmail.com', '0999999999', '', '', '', 'Representante'),
		    array('MARCIA GEORGINA', 'MOREIRA CAICEDO', 'Femenino', 'marciamoreira715@gmail.com', '', '', 'Guayacanes mz 189 v 11', '2824501', 'Representante'),
		    array('PATRICIA DEL ROCIO', 'VEINTIMILLA COELLO', 'Femenino', 'patriciacoello@gmail.com', '0992232392', '', '', '', 'Representante'),
		    array('VICTOR ANTONIO', 'SEMPERTEGUI ARELLANO', 'Femenino', 'victor_sempertegui@hotmail.com', '0997741298', '', 'Sauces 4 Mz.375 V.30', '042823696', 'Representante'),
		    array('CHRISTIAN JOSE', 'BRIONES CANTOS', 'Masculino', 'christian.briones@yahoo.com', '0998697684', '', '', '', 'Representante'),
		    array('FLOR MARIA', 'OTACOMA MORA', 'Femenino', 'florci_otac@hotmail.com', '0983638720', '', '', '', 'Representante'),
		    array('ERIKA YANIRE', 'BARRAGAN COELLO', 'Femenino', 'erikayumei@gmail.com', '', '', '', '', 'Representante'),
		    array('SHIRLEY PAOLA', 'SALAZAR MOSQUERA', 'Femenino', 'paitosm@hotmail.com', '', '', '', '', 'Representante'),
		    array('SORAYA FRANCISCA', 'LUCAS MONCAYO', 'Femenino', 'slucas@printit.ec', '0986493718', '', '', '', 'Representante'),
		    array('JOFFRE JOHNNY', 'CRUZ ALVARADO', 'Masculino', 'joffre.cruz2018@hotmail.com', '0990018086', '', '', '', 'Representante'),
		    array('EVELYN MARIELLA', 'PERERO REYES', 'Femenino', 'evelyn_perero@hotmail.com', '', '', '', '', 'Representante'),
		    array('ANTONIO XAVIER', 'VARGAS OBANDO', 'Femenino', 'xaviervargaso@hotmail.com', '0991616394', '', 'URBANIZACION ALAMEDA DEL RIO MZ-2783 V-06 array(MUCHO LOTE 2)', '3884609', 'Representante'),
		    array('ALBERTO', 'SPER SEMPERTEGUI', 'Femenino', 'sincorreo56@gmail.com', '', '', '', '', 'Representante'),
		    array('WISTERMAN UBALDO', 'ESCOBAR ESCOBAR', 'Masculino', 'ingwisterman@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('GLORIA ISAURA', 'OCHOA GOIBURO', 'Femenino', 'gloriadesigcho@gmail.com', '', '', '', '', 'Representante'),
		    array('KAREN ELENA', 'ICAZA ARBOLEDA', 'Femenino', 'karen_cool@hotmail.es', '', '', '', '', 'Representante'),
		    array('MANUEL', 'QUIÑONEZ ANZOATEGUI', 'Femenino', 'manuelquinonez521@gmail.com', '0986671698', '', '', '', 'Representante'),
		    array('MERCY BETTY', 'MADRID MORAN', 'Femenino', 'sincorreo58@gmail.com', '', '', '', '', 'Representante'),
		    array('JOSE ALEJANDRO', 'VASQUEZ LUZURIAGA', 'Femenino', 'javerntaservicios@gmail.com', '', '', '', '', 'Representante'),
		    array('OLGA FELICITA', 'MENENDEZ VILLAFUERTE', 'Femenino', 'olga.menendez@hotmail.es', '', '', 'Cdla.Guayacanes mz. 95 v.6', '2820949', 'Representante'),
		    array('MARIANA ANGELA', 'SOSA JAMA', 'Femenino', 'djmsalazar@hotmail.com', '', '', '', '', 'Representante'),
		    array('SALLY ZULEYKA', 'ROMERO VELEZ', 'Femenino', 'sally197305@gmail.com', '', '', '', '', 'Representante'),
		    array('GLENDA SHIRLEY', 'SUAREZ RUIZ', 'Femenino', 'glenditassruiz@hotmail.com', '', '', '', '', 'Representante'),
		    array('LEXY OSLITA', 'SOLORZANO MACAY', 'Femenino', 'andreabarrazueta@gmail.com', '0997738128', '', 'Brisas del Norte MzJ Solar 18', '045040118', 'Representante'),
		    array('IRINA MAGALY', 'ALCIVAR PINARGOTE', 'Femenino', 'sincorreo59@gmail.com', '', '', '', '', 'Representante'),
		    array('IVONNE VERONICA', 'BEDOYA GARCES', 'Femenino', 'joyce-mabe-@hotmail.com', '', '', '', '', 'Representante'),
		    array('PEDRO JESUS', 'ELAO FALCONES', 'Femenino', 'p_elao_f@hotmail.com', '', '', '', '', 'Representante'),
		    array('GUSTAVO MARIO', 'COELLO CAGUA', 'Femenino', 'gustavcoll@hotmail.com', '', '', '', '', 'Representante'),
		    array('GUILLERMO BARNABAY', 'ZARAMA MORALES', 'Femenino', 'barnaby.zarama@mail.com', '0984083565', '', '', '', 'Representante'),
		    array('RAQUEL ALEXANDRA', 'SOLORZANO ZAMBRANO', 'Femenino', 'rsolorzano01@hotmail.com', '', '', '', '', 'Representante'),
		    array('ANA CRISTINA', 'CISNEROS GARCIA', 'Femenino', 'anicis28@hotmail.com', '', '', 'Alborada 8va etapa mz.828 villa 1', '099217630/ 0962759330', 'Representante'),
		    array('Karla Bonny', 'Gilces Orozco', 'Masculino', 'k.arlago1909@gmail.com', '0988981582', '', 'La Joya brillante Mz10 villa 42', '2070331', 'Representante'),
		    array('MARIELA PAOLA', 'MERA ALCIVAR', 'Femenino', 'mariela.mera@hotmail.com', '', '', '', '', 'Representante'),
		    array('RICARDO LUTFALLAH', 'ESPINOZA AMAGUAÑA', 'Femenino', 'ricardoespinozaa@hotmail.com', '', '', '', '', 'Representante'),
		    array('GISSELLA PAULINA', 'BURBANO VERA', 'Femenino', 'pausegis@hotmail.com', '', '', '', '', 'Representante'),
		    array('CINTHYA BEATRIZ', 'CORDOVA ANCHUNDIA', 'Femenino', 'cinthia_2687@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA CRISTINA', 'LOPEZ PINCAY', 'Femenino', 'cristinalopez1982@hotmail.com', '', '', '', '', 'Representante'),
		    array('JANINA PAOLA', 'MONTALVAN THOMPSON', 'Femenino', 'janinita_07@hotmail.com', '', '', '', '', 'Representante'),
		    array('MARIA FIDELINA', 'ANDRADE PINARGOTE', 'Femenino', 'fidelinandrade@hotmail.com', '0998512361', '', '', '', 'Representante'),
		    array('CARLA MARIA', 'CASTRO RIVADENEIRA', 'Femenino', 'carlacastrorivadeneira@hotmail.com', '0985113788', '', '', '', 'Representante'),
		    array('LEYBER ROBINSON', 'DOMINGUEZ RODRIGUEZ', 'Femenino', 'domleyber@hotmail.com', '', '', '', '', 'Representante'),
		    array('DETSY DE JESUS', 'BRAVO HEMBA', 'Femenino', 'detsydj@hotmail.com', '', '', '', '', 'Representante'),
		    array('CARLOS ENRIQUE', 'JARRIN ESPIN', 'Femenino', 'carlosjarrinczs5@gmail.com', '0984790190', '', 'Sauces 4 Ms 373 Villa 29', '045066494', 'Representante'),
		    array('JENNY SAMANTHA', 'NARVAEZ PARRA', 'Femenino', 'akanesophia@gmail.com', '', '', '', '', 'Representante'),
		    array('LUIS EDUARDO', 'PAEZ DONOSO', 'Femenino', 'eduardo.paez.donoso@gmail.com', '', '', '', '', 'Representante'),
		    array('GLORIA', 'TORRICO LIMPIAS', 'Femenino', 'gloriatorricol2@gmail.com', '0996996949', '', 'Guayacanes MZ 19 V 30', '2620201', 'Representante'),
		    array('GISSELA MARICELA', 'CORDOVILLA ZAMORA', 'Femenino', 'kerlymaricela30@gmail.com', '', '', '', '', 'Representante'),
		    array('KARINA ISABEL', 'GONGORA MARTILLO', 'Femenino', 'karina.gongora@hotmail.com', '0994423633', '', 'Urbanización Villa Italia Etapa Bari Mz. 9 Villa 22', '045039814', 'Representante'),
		    array('MIRIAN ELIZABETH', 'JAIGUA ROJANO', 'Femenino', 'mielroja80@hotmail.com', '', '', '', '', 'Representante'),
		    array('ANABEL GABRIELA', 'MOREJON ENRIQUEZ', 'Femenino', 'anabelita_28j@yahoo.com', '', '', '', '', 'Representante'),
		    array('ESTEFANIA FERNANDA', 'MORA OLAYA', 'Femenino', 'estefymora_olaya@hotmail.com', '', '', '', '', 'Representante'),
		    array('WILLIAM DE JESUS', 'RAMIREZ MONTOYA', 'Femenino', 'clarita0305@life.com', '', '', '', '', 'Representante'),
		    array('SARA EONEMY', 'PALACIOS OLIVA', 'Femenino', 'spaloliva@gmail.com', '1111111111', '', '', '', 'Representante'),
		    array('CARLOS JULIO', 'ROBLES RIZZO', 'Masculino', 'krlos_k2@hotmail.com', '0986707371', '', 'La Rioja etapa Bolonia MZ 5 villa 2', '042827599', 'Representante'),
		    array('ROXANA ELIZABETH', 'SANCHEZ MACIAS', 'Masculino', 'roxanasanchezmacias@gmail.com', '1111111111', '', '', '', 'Representante'),
		    array('YARIMA MAGDALENA', 'DIAZ DIAS', 'Femenino', 'yarima.diaz@hotmail.com', '0986043278', '', 'Paraiso del rio 2', '', 'Representante'),
		    array('CHRISTIAN EFRAIN', 'ABAD MOSCOSO', 'Masculino', 'sincorreo99@gmail.com', '1234567890', '', '', '', 'Representante'),
		    array('JORGE ALFREDO', 'ALMENDARIZ CARPIO', 'Masculino', 'jorgealmendariz@gmail.com', '1111111111', '', '', '', 'Representante'),
		    array('LEANA BEATRIZ', 'MIRANDA POALASIN', 'Femenino', 'myrhuska@hotmail.com', '0997477791', '', 'guayacanes  Mz 98b villa 14', '042822557', 'Representante'),
		    array('RUIXIANG', 'LIN', 'Masculino', '1404922723@qq.com', '1111111111', '', '', '', 'Representante'),
		    array('ADRIANA STEFANIA', 'HARO GONZALEZ', 'Femenino', 'aharog@hotmail.com', '1111111111', '', '', '', 'Representante'),
		    array('CLARITA CAROLA', 'AGUILAR RAMIREZ', 'Femenino', 'claaguilar69@hotmail.com', '0981763371', '', '', '', 'Representante'),
		    array('KATTY CLAUDIA', 'NAVARRETE ORTIZ', 'Femenino', 'claudina52001@hotmail.com', '1111111111', '', '', '', 'Representante'),
		    array('SUCRE MAURICIO', 'PALACIOS GRIJALVA', 'Masculino', 'julipierijessimauro@hotmail.com', '1111111111', '', 'CDLA ALBORADA 6TA ETAPA MZ 631 VILLA 06', '042920155', 'Representante'),
		    array('ELKIN SNEIDER', 'MONTOYA OCHOA', 'Masculino', 'elkinmontoya@gmail.com', '1111111111', '', '', '', 'Representante'),
		    array('OSCAR ALFREDO', 'RUIZ CENTURION', 'Masculino', 'chop_suey_16@hotmail.com', '1111111111', '', '', '', 'Representante'),
		    array('JORGE WASHINGTON', 'OSORIO QUINTO', 'Masculino', 'josorio@pryscom.ec', '0979989316', '', 'VillaClub Etapa Estelar Mz. 12 Villa 43', '042164945', 'Representante'),
		    array('MARTHA JACQUELINE', 'ZAMBRANO SOLORZANO', 'Femenino', 'dra.marthazs@gmail.com', '1111111111', '', '', '', 'Representante'),
		    array('FAUSTO ANDRES', 'TRIVIÑO BUSTOS', 'Masculino', 'faustoyfa@hotmail.com', '0939439702', '', '', '042177609', 'Representante'),
		    array('SUSAN CAROLINA', 'COBO PACHECO', 'Femenino', 'susan.cobo@hotmail.com', '0996549802', '', '', '', 'Representante'),
		    array('JACQUELINE', 'HINOSTROZA ARROBA', 'Femenino', 'jaquyhinos1@hotmail.com', '1111111111', '', '', '', 'Representante'),
		    array('MARYORI YESSENIA', 'BRAVO VELASQUEZ', 'Femenino', 'mybravo@pichincha.com', '1111111111', '', '', '', 'Representante'),
		    array('INGRID VERONICA', 'TROYA VERA', 'Femenino', 'ingridverotv_23.74@hotmail.com', '0986379294', '', '', '', 'Representante'),
		    array('CLAUDIA MARIA', 'VELASQUEZ RUEDA', 'Femenino', 'cami10clau@hotmail.com', '1111111111', '', '', '', 'Representante'),
		    array('CLAUDIA MARLENE', 'BOSQUEZ JARRIN', 'Masculino', 'claudyhec@hotmail.com', '1111111111', '', '', '', 'Representante'),
		    array('FRANKLIN JAVIER', 'IZURIETA CALLE', 'Masculino', 'sincorreo200@gmail.com', '1111111111', '', '', '', 'Representante'),
		    array('JENNY ELIZABETH', 'VILLEGAS ULLOA', 'Femenino', 'elisky_dulce@hotmail.com', '1111111111', '', '', '', 'Representante'),
		    array('KARLA', 'COBA CHAVEZ', 'Femenino', 'karlacoba894@gmail.com', '0996939789', '', 'COL. ALBORADA MZ. 773  V.12', '', 'Representante'),
		    array('SANTIAGO JAVIER', 'RUEDA ZAMBRANO', 'Masculino', 'ingsaru@hotmail.com', '0999999999', '', '', '', 'Representante'),
		    array('AIDE ELENA', 'LOPEZ MONTES', 'Femenino', 'chinaelenal@hotmail.com', '0993593621', '', '', '', 'Representante'),
		    array('EMILIO ALBERTO', 'MORLA LARREA', 'Masculino', 'morla_e65@yahoo.com', '0958971181', '', '', '', 'Representante'),
		    array('MANUEL FRANCISCO', 'SOLORZANO CHONILLO', 'Masculino', 'anitalopeznarvaez@hotmail.com', '0960068752', '', '', '', 'Representante'),
		    array('KENNY PAUL', 'YCAZA MARIDUEÑA', 'Masculino', 'kenycaza@gmail.com', '0994016109', '', '', '', 'Representante'),
		    array('JENNY MARIELA', 'PRECIADO VERA', 'Femenino', 'marielajenny2011@hotmail.com', '0994188377', '', '', '', 'Representante'),
		    array('ANABEL', 'MONTERO', 'Femenino', 'anabel.montero@gmail.com', '0999999999', '', '', '', 'Representante'),
		    array('ROSARIO DEL PILAR', 'VELEZ VERA', 'Femenino', 'rvelez1963@hotmail.com', '', '', '', '', 'Representante'),
		);
		$role = Sentinel::findRoleByName('Representante');
        for ($i=0; $i < count($users); $i++) {
            //print($key['email']);
              
            $insert =[
                'email' => $users[$i][3],
                'password' => 'soyRepresentante'
            ];
            $user =  Sentinel::registerAndActivate($insert);
            $role->users()->attach($user);
            \DB::table('users_profile')->insert(array(
                'nombres'       => $users[$i][0],
                'apellidos'     => $users[$i][1],
                'sexo'          => $users[$i][2],
                'correo'        => $users[$i][3],
                'movil'         => $users[$i][4],
                'bio'           => $users[$i][5],
                'dDomicilio'   => $users[$i][6],
                'tDomicilio'   => $users[$i][7],
                'cargo'         => 'Representante',
                'userid'        => $user->id
            ));
        } 
    }
}
